### ISSUE TITLE
Toolbar not working after updated to v2.1.3

### ISSUE THREAD

**Issue by raaynaldo** [uiwjs/react-md-editor#101]
`preview="preview"` is working fine, but suddenly when I use the toolbar there is not markdown syntax rendered to the text area.

https://codesandbox.io/s/markdown-editor-for-react-99-7ulng

**Comment by jaywcjlove** [comment]
@raaynaldo Did not understand what it meant.

**Comment by raaynaldo** [comment]
@jaywcjlove When I click bold, italic, or everything in the toolbar, it doesn't work. In sandbox link also didn't work.
https://codesandbox.io/s/markdown-editor-for-react-99-7ulng

**Comment by jaywcjlove** [comment]
@raaynaldo The old version style import in the example and I have deleted it.

> Old Style: https://unpkg.com/@uiw/react-md-editor@1.6.0/dist/markdown-editor.css

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/106044140-4c2d1900-611a-11eb-81ea-55e25cef0112.png)

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/106044452-b6de5480-611a-11eb-9322-443039e17f00.png)

**Comment by raaynaldo** [comment]
@jaywcjlove sorry, I think there is a misunderstanding. So if we click the bold button in the toolbar, it will be adding `****`

![react-md-editor(v2 1 2)](https://user-images.githubusercontent.com/22878284/106053178-7d74fd00-60b8-11eb-9016-b41e4e13f848.gif)

After fixing preview props v2.1.3, the toolbar not working at all.

![react-md-editor(v2 1 4)](https://user-images.githubusercontent.com/22878284/106053198-849c0b00-60b8-11eb-800a-52079c06c0d7.gif)

**Comment by jaywcjlove** [comment]
@raaynaldo Upgrade `+ @uiw/react-md-editor@2.1.5`, thx!

**Comment by raaynaldo** [comment]
Hi thank you for the update, it is work now. However, I found another bug.

try to change to the last version in this sandbox
https://codesandbox.io/s/markdown-editor-for-react-96-forked-rzrnj?file=/index.js

when you change the value in the input box, it will not change the text area. :(

**Comment by jaywcjlove** [comment]
@raaynaldo thx!  it's my fault...

**Comment by jaywcjlove** [comment]
@raaynaldo Upgrade `+ @uiw/react-md-editor@2.1.7`

**Comment by jaywcjlove** [comment]
@raaynaldo Another minor problem was found. Upgrade `+ @uiw/react-md-editor@2.1.8` :(

**Comment by raaynaldo** [comment]
@jaywcjlove what the minor problem is about? Luckily, I just did my presentation about my project that utilized this library, and react-md-editor is doing well. I will share my app If I have already hosted it. Thank you so much for creating this library. You can close this issue if the issue is done.

**Comment by jaywcjlove** [comment]
@raaynaldo thx!
