### ISSUE TITLE
TypeError: text is undefined

### ISSUE THREAD

**Issue by Formalibus** [uiwjs/react-md-editor#103]
Didn't found any information on stackoverflow, might be I didn't good search
I was on 2.1.2 version but with update this occured
![изображение](https://user-images.githubusercontent.com/31123287/106360285-cee3ed00-6341-11eb-8467-9fa0fd6896fa.png)
![изображение](https://user-images.githubusercontent.com/31123287/106360350-25e9c200-6342-11eb-9148-668bba3c03e8.png)

**Comment by jaywcjlove** [comment]
@Formalibus Upgrade `v2.1.8`

**Comment by Formalibus** [comment]
> 
> 
> @Formalibus Upgrade `v2.1.8`

I was actually at v2.1.8 then this error occured
I am on v2.1.2 it's working

**Comment by jaywcjlove** [comment]
Can you provide an example?
@Formalibus

**Comment by Formalibus** [comment]
here my imports 
![изображение](https://user-images.githubusercontent.com/31123287/106363499-2048a800-6353-11eb-9eae-85c6d464d567.png)

here I call it
`<div className="row markdownEditor">`
`          <div className="col-sm">`
`            <MDEditor preview="edit" height="730" onChange={setContent} />`
`          </div>`
 `         <div className="col-sm">`
`            <MDEditor.Markdown source={content} />`
 `         </div>`
`        </div>`
now it working on v2.1.2
![изображение](https://user-images.githubusercontent.com/31123287/106363526-48d0a200-6353-11eb-98f0-116992f16295.png)

**Comment by Formalibus** [comment]
now I updated md editor
![изображение](https://user-images.githubusercontent.com/31123287/106363641-eb892080-6353-11eb-9d46-d9f01f46148a.png)
and got this
![изображение](https://user-images.githubusercontent.com/31123287/106363649-fba10000-6353-11eb-951c-449e004bfa2d.png)
TypeError: text is undefined
matchGrammar
C:/Users/Udodelighed/react_lessons/destination_pamir/node_modules/prismjs/prism.js:887

  884 | 
  885 | var str = currentNode.value;
  886 | 
> 887 | if (tokenList.length > text.length) {
      | ^  888 | 	// Something went terribly wrong, ABORT, ABORT!
  889 | 	return;
  890 | }

tokenize
C:/Users/Udodelighed/react_lessons/destination_pamir/node_modules/prismjs/prism.js:655

  652 | 	var tokenList = new LinkedList();
  653 | 	addAfter(tokenList, tokenList.head, text);
  654 | 
> 655 | 	matchGrammar(text, tokenList, grammar, tokenList.head, 0);
      | ^  656 | 
  657 | 	return toArray(tokenList);
  658 | },

highlight
C:/Users/Udodelighed/react_lessons/destination_pamir/node_modules/prismjs/prism.js:613

  610 | 		language: language
  611 | 	};
  612 | 	_.hooks.run('before-tokenize', env);
> 613 | 	env.tokens = _.tokenize(env.code, env.grammar);
      | ^  614 | 	_.hooks.run('after-tokenize', env);
  615 | 	return Token.stringify(_.util.encode(env.tokens), env.language);
  616 | },

highlight
C:/src/components/TextArea/index.tsx:36

  33 | const [value, setValue] = useState(props.value);
  34 | const highlight = () => {
  35 |   const pre = preElm.current;
> 36 |   const html = Prism.highlight(value as string, Prism.languages.markdown, 'markdown');
     | ^  37 |   pre!.innerHTML = `${html}<br />`;
  38 | };
  39 | useEffect(() => {

./node_modules/@uiw/react-md-editor/lib/esm/components/TextArea/index.js/__webpack_exports__.default</<
C:/src/components/TextArea/index.tsx:51

  48 |   }
  49 | }, [props.value]);
  50 | 
> 51 | useEffect(() => highlight(), [value]);
     | ^  52 | useEffect(() => {
  53 |   if (props.autoFocus && textElm.current) {
  54 |     textElm.current.focus();

**Comment by jaywcjlove** [comment]
@Formalibus I cannot help you resolve the error. 

Project example ? Put it in the repositories?

**Comment by Formalibus** [comment]
no need, thanks )))
just wanted to notify about issue
if you want I can close an issue

**Comment by jaywcjlove** [comment]
:(

**Comment by ifbarrera** [comment]
Hi, I'm also getting this error on `2.1.8`, react v. `16.14.0`.

Usage:

```
import MDEditor from '@uiw/react-md-editor';

<MDEditor value={"sample value"} autoFocus={0} />
```

Error:
![image](https://user-images.githubusercontent.com/3156796/107561192-3e60a480-6bac-11eb-85f1-4d257fe0620d.png)

**Comment by jaywcjlove** [comment]
@ifbarrera https://codesandbox.io/s/markdown-editor-for-react-forked-2fzdr

**Comment by ifbarrera** [comment]
@jaywcjlove updated your code sandbox: https://codesandbox.io/s/markdown-editor-for-react-forked-19hfr?file=/index.js

Seems to be related to having `MDEditor` as part of a form, and setting its value with `React.useEffect`.

In my app, I use this to in a form to pre-populate a previously saved value.

**Comment by jaywcjlove** [comment]
@ifbarrera 

```diff
<Form.Item
  name="editor"
+   initialValue="test"
>
  <MDEditor value={"sample value"} autoFocus={0} />
</Form.Item>
```

**Comment by ifbarrera** [comment]
You can't dynamically change `initialValue` or `defaultValue` on forms based on state. https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

This is why I use the `React.useEffect` hook.

**Comment by jaywcjlove** [comment]
@ifbarrera  https://ant.design/components/form/#components-form-demo-customized-form-controls

**Comment by an-lee** [comment]
Got the same issue when upgrade to `2.1.8` from `2.1.2`.  Also using with `antd` form component.

Solved by providing an `initialValue`.

**Comment by an-lee** [comment]
btw, for `2.1.8` version, the props `autoFocus` seems not working. It always auto focus even `autoFocus={false}` is set. @jaywcjlove
