### ISSUE TITLE
Error when edit Katex

### ISSUE THREAD

**Issue by icimence** [uiwjs/react-md-editor#105]
即使在提供的sandbox的样例中在新的一行中直接输入```即可引发错误。应该是还没有输入代码块的语言，但是已经开始渲染导致的。截图如下：
![image](https://user-images.githubusercontent.com/34977758/106604141-33998480-659a-11eb-8b4b-45f8bcb61ae4.png)

**Comment by jaywcjlove** [comment]
@icimence 示例已更新

**Comment by icimence** [comment]
看到了感谢
