### ISSUE TITLE
Can I customize the renderer?

### ISSUE THREAD

**Issue by jongjunpark** [uiwjs/react-md-editor#108]
I checked some bugs during use.

please try below text in editor
```
- text
  - (tab: 1)
```
```
- text
    - (tab: 2)
```

```
- text
      - (tab: 3) 
```
```
- text
text2
  - (tab: 1) 
```
```
    text (tab:2)
```
```
1. text
1. text
1. text


1. text
```

I think this problem cause of react-markdown.
could you fix this bug?
If you can't fix this bug, please tell me about how to customize it.

**Comment by jaywcjlove** [comment]
I used it and it seemed correct. @jongjunpark

**Comment by jongjunpark** [comment]
okay, can you tell me how to customize the renderer?
I want to change some grammar in markdown
for example,
```
    text (tab: 2)
```
I want it didn't make the block grammar.

**Comment by jaywcjlove** [comment]
@jongjunpark 

`previewOptions?`: [ReactMarkdown.ReactMarkdownProps](https://github.com/uiwjs/react-markdown-preview/tree/55564d16e98591c54236fe3b57cc27b5dbae3004#options-props) - This is reset @uiw/react-markdown-preview settings.

**Comment by jongjunpark** [comment]
@jaywcjlove thanks! 👍

**Comment by EnzoVezzaro** [comment]
Hi guys, is there a wat to change @uiw/react-markdown-preview with a custom one? I need to replace the preview component, but I haven't been able to make it work yet. What do you guys suggest?

**Comment by jaywcjlove** [comment]
@EnzoVezzaro #429

**Comment by EnzoVezzaro** [comment]
Thank you very much @jaywcjlove this is what I needed. Thanks
