### ISSUE TITLE
Bold text issue

### ISSUE THREAD

**Issue by Mkdantas** [uiwjs/react-md-editor#114]
Hey everyone,

I don't know if i'm the only one, but when i try using bold text in my editor it gives a strange spacing everytime and it breaks everything because i cant find myself in the text anymore.

![image](https://user-images.githubusercontent.com/50972667/108520843-deec4e00-72a9-11eb-9f1f-3cf1ec0c7f6b.png)

has anyone seen this issue?

**Comment by jaywcjlove** [comment]
@Mkdantas Is there a style conflict?

**Comment by Mkdantas** [comment]
I tried looking into it and it doesn't seem like it. It happens with bold, italic and lined text

**Comment by jaywcjlove** [comment]
@Mkdantas I have no way to reproduce your problem.

**Comment by Mkdantas** [comment]
Alright, then if it doesn't happen for anyone else it could really be a styles issue. I will look into it this week!

**Comment by Mkdantas** [comment]
Thank you @jaywcjlove

**Comment by diegoolavarria** [comment]
Hi, is happening to me as well. Did you were able ot fix it?

**Comment by Mkdantas** [comment]
Yes!! The problem is that the component uses common class names in css so it is really easy to have your code override the css of the component
