### ISSUE TITLE
Does not work with NextJS (duplicate of #52)

### ISSUE THREAD

**Issue by feRpicoral** [uiwjs/react-md-editor#135]
This is a relatively simple fix yet crucial to improve this package's popularity. 

There's already an [issue on this](https://github.com/uiwjs/react-md-editor/issues/52) but for some reason it's closed. All the "fixes" suggested there are unreliable (edit `node_modules` directly) or unencouraged (using the deprecated package `@zeit/next-css`)

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

@feRpicoral

**Comment by jaywcjlove** [comment]
I am sure [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) is a perfect solution. :)
