### ISSUE TITLE
Improve toolbar button focus styling for keyboard users

### ISSUE THREAD

**Issue by jmtes** [uiwjs/react-md-editor#142]
The following screenshots show that, if a toolbar button has focus, it's not very clear because the styling doesn't look any different from the default state.
![MDEToolbarButtonFocus](https://user-images.githubusercontent.com/38450133/114474162-7e430880-9baa-11eb-9d71-4da34bac1377.PNG)

![Screenshot (87)](https://user-images.githubusercontent.com/38450133/114474170-813df900-9baa-11eb-8bd6-3cfeb56be2fc.png)

In order to make it more accessible for people that rely on the keyboard to navigate pages, the buttons should look as they do on hover when they receive focus.

**Comment by jaywcjlove** [comment]
@jmtes thx! Upgrade `+ @uiw/react-md-editor@3.0.0-beta.5`
