### ISSUE TITLE
prismjs dependency CVE

### ISSUE THREAD

**Issue by kamal94** [uiwjs/react-md-editor#144]
![image](https://user-images.githubusercontent.com/7926046/114723873-03443400-9d09-11eb-86f9-3d0b306af1f7.png)
The only vulnerability I have in my project comes from prismjs which is a dependency of react-md-editor.

I think the minor version update is compatible so it should be a straightforward fix! :)

**Comment by jaywcjlove** [comment]
@kamal94 Upgrade `+ @uiw/react-md-editor@3.0.0-beta.6`
