### ISSUE TITLE
Checklist Bug

### ISSUE THREAD

**Issue by fellars** [uiwjs/react-md-editor#146]
I made a video explaining the bug.  Seeing the checklist on a second line in the preview. Also seeing the checklist with a bullet point in front of it at times.

See first half of this video: https://www.loom.com/share/2b9a883f95e043508353424e6a2ebdd9

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/115744381-1b7d1880-a3c5-11eb-9c45-64711c39ecc4.png)
I did not reproduce your bug. @fellars

**Comment by jaywcjlove** [comment]
> ![image](https://user-images.githubusercontent.com/1680273/115744381-1b7d1880-a3c5-11eb-9c45-64711c39ecc4.png)
> I did not reproduce your bug. @fellars

Your text content has special characters?

**Comment by fellars** [comment]
I am seeing it with the default text on the website. made new video showing it with the example text:
https://www.loom.com/share/304302b527d94b37b073dd518770a5e6?from_recorder=1&focus_title=1

**Comment by jaywcjlove** [comment]
@fellars Upgrade `+ @uiw/react-md-editor@3.0.0-beta.7`
