### ISSUE TITLE
NextJS 10 or above Framework issue "Global CSS cannot be imported from within node_modules"

### ISSUE THREAD

**Issue by Hassaan016** [uiwjs/react-md-editor#148]
Dear All,
              I created a NextJS project and installed the react-markdown-editor via npm. When I try to run my NextJS project the following error message appears:

**Error**
`Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules\@uiw\react-markdown-preview\lib\esm\index.js`

And the possible reason according to NextJS documentation:
[https://nextjs.org/docs/messages/css-npm](url)

It will be really great if "react-markdown-editor" can be ported for NextJS framework properly.

**Note**:
- Similar issue: [https://github.com/uiwjs/react-md-editor/issues/52](url)
- As a solution to similar issue as mine **current version of NextJS 10 or above**  have deprecated the use of "@zeit/next-css" and don't recommend to use it.
- Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
Regards,
MHS

**Comment by Hassaan016** [comment]
Here found the "codesandbox" project link for NextJs framework: [https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js](url)

- Export the project as .zip from "codesandbox" and extract to your desired location
- navigate to the extracted directory and use the "npm install" command to install all the dependencies.
- "npm run dev" to run the project

**Comment by Hassaan016** [comment]
Here found the "codesandbox" project link for NextJs framework: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js

Export the project as .zip from "codesandbox" and extract to your desired location
navigate to the extracted directory and use the "npm install" command to install all the dependencies.
"npm run dev" to run the project

**Comment by JasonAtallah** [comment]
Is there an update to this? I'm running into the same issue

**Comment by fervillalbag** [comment]
same problem

**Comment by Frostbourn** [comment]
Same problem
