### ISSUE TITLE
Can not access commandOrchestrator anywhere since v2

### ISSUE THREAD

**Issue by chinfeng** [uiwjs/react-md-editor#150]
Is this feature miss since v2 ? I can not access commandOrchestrator anywhere since v2. I worked under v1.

```jsx
const r = useRef();
function exec() {
  if (r.current) {
    r.current.commandOrchestrator.executeCommand({ execute(state, api) { /* ... */ } });
  }
}
return (
  <>
    <button onClick={exec}>execute command from here</button>
    <MDEditor ref={r}/>;
  </>
)
```

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/117168876-23907b80-adfb-11eb-8666-884fc504266f.png)

Upgrade `+ @uiw/react-md-editor@3.0.7`
