### ISSUE TITLE
Close Group Command on Click

### ISSUE THREAD

**Issue by on2air** [uiwjs/react-md-editor#152]
When using the group for titles like the example, it should close the group list when you click on one of the items.  Right now, it stays open and covers the text area where you inserted the title:

![image](https://user-images.githubusercontent.com/61258595/116450405-7fb23900-a818-11eb-8a11-ded74d71ccea.png)

**Comment by jaywcjlove** [comment]
@on2air Upgrade `+ @uiw/react-md-editor@3.0.1`

**Comment by saran13raj** [comment]
@jaywcjlove This still seems to be an issue in the latest versions!

Browser: Brave v 1.41.100
OS: macOS Monterey v 12.1

Tested with react-md-editor v3.3.3 and v3.11.0
https://codesandbox.io/embed/react-md-editor-custom-toolbars-m2n10?fontsize=14&hidenavigation=1&theme=dark
