### ISSUE TITLE
codeBlock is missing from index.ts exports

### ISSUE THREAD

**Issue by on2air** [uiwjs/react-md-editor#153]
so not able to use in custom toolbar like the others.

**Comment by jaywcjlove** [comment]
@on2air  Upgrade `+ @uiw/react-md-editor@2.1.11`

**Comment by on2air** [comment]
Thank you @jaywcjlove I'm able to now add to toolbar and it inserts the markdown, but now it doesn't render the code block in the  previewer. Does the previewer support code blocks?

**Comment by on2air** [comment]
never mind - it was an issue on my end. all good now. thank you for speedy response.
