### ISSUE TITLE
TypeError: Cannot read property 'rest' of undefined

### ISSUE THREAD

**Issue by pichjinnapat** [uiwjs/react-md-editor#155]
Hi, I got an error "TypeError: Cannot read property 'rest' of undefined" while a month ago this never happen.
Do you have any solution?

<img width="1101" alt="Screen Shot 2564-04-30 at 21 17 56" src="https://user-images.githubusercontent.com/73090829/116708314-c8751800-a9f9-11eb-9c8f-4268a5e01e54.png">

**Comment by jaywcjlove** [comment]
@pichjinnapat Can provide examples?

**Comment by jaywcjlove** [comment]
@pichjinnapat I guess it might be the problem. 

Upgrade `+ @uiw/react-md-editor@3.0.2`
