### ISSUE TITLE
Update react-markdown to the latest version

### ISSUE THREAD

**Issue by rafaelguedes** [uiwjs/react-md-editor#156]
Before anything else: thanks for this cool editor.

Is there any chance of updating `react-markdown` to its latest version (6.0.1), to support props such as `remarkPlugins` and `components`?

Thanks! 🙂

**Comment by jaywcjlove** [comment]
Upgrade `+ @uiw/react-md-editor@3.0.4` @rafaelguedes

**Comment by rafaelguedes** [comment]
Thanks a lot, @jaywcjlove.
What a fast help!
