### ISSUE TITLE
Bulleted list is not add bulleted auto when press return key (mac os)

### ISSUE THREAD

**Issue by ndhhien27** [uiwjs/react-md-editor#158]
When I used the latest version of `react-md-editor` and `react@16.10.2`, the bulleted list is not adding bulleted auto when pressing the return key. Do you have any solution to fix it without upgrade react version?
I tried downgrade `react-md-editor` version but it not work.

**Actual:**
<img width="1792" alt="Screen Shot 2021-05-05 at 09 37 22" src="https://user-images.githubusercontent.com/43933954/117091807-a62b2380-ad86-11eb-84d5-623a8bb227c4.png">

**Version used:**
react@16.10.2
@uiw/react-md-editor@3.0.4

**Comment by jaywcjlove** [comment]
@ndhhien27 
This example: https://codesandbox.io/s/markdown-editor-for-q6h1n
Confirm that there is a problem, currently I don't know what caused the problem.

Solution: Upgrade `react@17+`

**Comment by ndhhien27** [comment]
@jaywcjlove Hope you can fix it soon. My project is using the old version react and I can't upgrade it as it will affect other important third libraries. Thank you so much

**Comment by jaywcjlove** [comment]
@ndhhien27 Upgrade `+ @uiw/react-md-editor@3.3.3`
