### ISSUE TITLE
Scrolling on preview is not scrolling the editor since v3.0.0

### ISSUE THREAD

**Issue by rafaelguedes** [uiwjs/react-md-editor#159]
Until v2.1.11, if you scroll the preview area, the editor will scroll simultaneously.
From v3.0.0 onwards, if you scroll the preview area, the editor will not scroll.

Can you bring this feature back?

Thanks. 🙂

**Comment by jaywcjlove** [comment]
@rafaelguedes Upgrade `+ @uiw/react-md-editor@3.0.5`

**Comment by rafaelguedes** [comment]
Thanks, once again, @jaywcjlove.
It's working! 👍
