### ISSUE TITLE
enable spellcheck

### ISSUE THREAD

**Issue by stevemk14ebr** [uiwjs/react-md-editor#169]
https://github.com/uiwjs/react-md-editor/blob/60fb1569d70efb4e8e42722281fe31a27c805078/src/components/TextArea/Textarea.tsx#L35

Allow this to be configurable

**Comment by jaywcjlove** [comment]
@stevemk14ebr Upgrade `+ @uiw/react-md-editor@3.0.9`

**Comment by stevemk14ebr** [comment]
this worked thank you for updating so fast
