### ISSUE TITLE
Markdown editor overflow at small size

### ISSUE THREAD

**Issue by serendipity1004** [uiwjs/react-md-editor#173]
![Screen Shot 2021-05-22 at 2 34 59 PM](https://user-images.githubusercontent.com/20388249/119215799-efab9a80-bb0a-11eb-852e-db87d4ca9388.png)

it's a 425x759 size screen in chrome and editor content seems to overflow.

```jsx
      <MDEditor
        value={MARKDOWN_SAMPLE}
        preview="edit"
        height={400}
        visiableDragbar={false}
        previewOptions={{
          skipHtml: true,
        }}
      />
```

above is the simple settings I'm using.

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/119234177-0c71bd80-bb5f-11eb-80bc-6e5483d8d29e.png)

@serendipity1004 May have style conflicts

https://codesandbox.io/s/markdown-editor-for-react-173-6ttjv?file=/index.js

**Comment by serendipity1004** [comment]
@jaywcjlove yea I think you're right. I can't seem to find which style is conflicting tho.

**Comment by serendipity1004** [comment]
After a further investigation it actually was nothing to do with style conflict. I was having this issue in the chrome dev tools (I have no idea if it also happens in real mobile devices) and It seems that if you set the MDEditor width to certain value (explicit pixels or simple 100%) the issue gets resolved. If you don't, as you resize the screen using dev tools, the bottom textarea will overflow just as much as how much more space toolbar eats up.

**Comment by serendipity1004** [comment]
add width like below
```
<MDEditor
  style={{
    width: "100%",
  }}
  value={MARKDOWN_SAMPLE}
  height={400}
/>
```
