### ISSUE TITLE
Bookmarks are not working

### ISSUE THREAD

**Issue by shajil-t** [uiwjs/react-md-editor#174]
Headers doesn’t seems to be generating id when rendering as HTML hence the bookmarks are not working, is there any workaround for bookmarks to work?

[@uiw/react-md-editor": "3.0.8"]

![Md](https://user-images.githubusercontent.com/76836201/119323682-43d78b80-bc7f-11eb-8334-a87062644169.jpg)

**Comment by jaywcjlove** [comment]
use `previewOptions.remarkPlugins` props. [remark plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins)

```jsx
import slug from 'remark-slug'

<MDEditor
  value={value}
  onChange={setValue}
  previewOptions={{
    remarkPlugins: [slug]
  }}
/>
```

@shajil-t

**Comment by shajil-t** [comment]
> use `previewOptions.remarkPlugins` props. [remark plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins)
> 
> ```js
> import slug from 'remark-slug'
> 
> <MDEditor
>   value={value}
>   onChange={setValue}
>   previewOptions={{
>     remarkPlugins: [slug]
>   }}
> />
> ```
> 

Thank you so much for the help, much appreciated, this now works on Editor Preview, however I would like to have this plugin for `<MDEditor.Markdown>` as well, how can use I use that please?

**Comment by jaywcjlove** [comment]
```jsx
import slug from 'remark-slug'

<MDEditor.Markdown
  previewOptions={{
    remarkPlugins: [slug]
  }}
/>
```

@shajil-t

**Comment by shajil-t** [comment]
> ```js
> import slug from 'remark-slug'
> 
> <MDEditor.Markdown
>   previewOptions={{
>     remarkPlugins: [slug]
>   }}
> />
> ```
> 
> @shajil-t

This doesn't seems to be working, there are no id's for headers when rendered in `<MDEditor.Markdown>`

**Comment by jaywcjlove** [comment]
```jsx
import slug from 'remark-slug'

<MDEditor.Markdown
  remarkPlugins={[slug]}
/>
```

@shajil-t

**Comment by shajil-t** [comment]
> ```js
> import slug from 'remark-slug'
> 
> <MDEditor.Markdown
>   remarkPlugins={[slug]}
> />
> ```
> 
> @shajil-t

This works 👍   Thank you
