### ISSUE TITLE
Programmatic field clearing does not work correctly

### ISSUE THREAD

**Issue by RomanChumakov** [uiwjs/react-md-editor#176]
Hello!
I found that when setting the md-editor value programmatically, md-editor appears to be half-cleared. The Markdown is cleared immediately. But the Textarea is not cleared until I switch to the preview mode and then back to previous mode.
It looks like the Textarea is not updated when the value is changed directly, until it is refreshed by changing mode.

**Comment by jaywcjlove** [comment]
@RomanChumakov Can you provide a reproducible example?

**Comment by jaywcjlove** [comment]
https://github.com/RomanChumakov/react-md-editor-bug-demonstration/blob/97ab1b703d3d6ee22630ac5f6375d04b796532fa/src/App.js#L22

```diff
<MDEditor
    className = "product-md-editor"
    onChange = {value => formik.setFieldValue('text', value)}
-    value = {formik.values.text}
+    value = {formik.values.text || ''}
/>
```

@RomanChumakov

**Comment by RomanChumakov** [comment]
@jaywcjlove
Thank you for such a quick response!
