### ISSUE TITLE
Support vite

### ISSUE THREAD

**Issue by yuyichen** [uiwjs/react-md-editor#181]
我使用的vite作为脚手架
本地运行OK，打包后发布后，运行报错，看代码初步判断是代码顺序有问题，不清楚是脚手架导致的还是依赖本身导致的，
![image](https://user-images.githubusercontent.com/8286053/120781521-ba1b9e00-c55b-11eb-89af-f540e7bbce49.png)

![image](https://user-images.githubusercontent.com/8286053/120781767-f5b66800-c55b-11eb-80f6-1e284b7a065f.png)

![image](https://user-images.githubusercontent.com/8286053/120781829-0535b100-c55c-11eb-9c96-95b9da6ccb3b.png)

![image](https://user-images.githubusercontent.com/8286053/120781684-df101100-c55b-11eb-82d4-ae33d916f8f4.png)

**Comment by jaywcjlove** [comment]
@yuyichen 具体不太清楚 vite 的编译过程干了什么，解决不了你的问题，你可以去 vite 里面搜索试一试

**Comment by jaywcjlove** [comment]
@yuyichen 要做什么样的操作支持 vite 呢？

**Comment by yuyichen** [comment]
我先试试换成其他脚手架吧

**Comment by yuyichen** [comment]
试了 create-react-app脚手架下正常，看来是vite的锅
