### ISSUE TITLE
Command to bundle entire library into single js?

### ISSUE THREAD

**Issue by on2air** [uiwjs/react-md-editor#191]
Im not familiar with all the build libraries. Is there an easy way I could create a bundle.js of the entire library and dependancies?

Use case is trying to use this in a single page html file via a <script url=""/>  I can host the bundled file, just need to get everything into a bundle.

Maybe its not easily possible...

**Comment by jaywcjlove** [comment]
[![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-md-editor@3.4.9/file/README.md)

![image](https://user-images.githubusercontent.com/1680273/125067607-120f6c80-e0e7-11eb-87b3-3657e03360d8.png)


@on2air
