### ISSUE TITLE
Simultaneous scroll is not working properly

### ISSUE THREAD

**Issue by rafaelguedes** [uiwjs/react-md-editor#196]
The simultaneous scroll feature - scrolling on the right side will auto-scroll the left side and vice versa - is not working as expected when you reload the page.

If you reload the page it randomly stops working as you can see in the gif below.
Can you, please, try to fix this?

![Markdown-Editor-for-React-CodeSandbox_1](https://user-images.githubusercontent.com/7645688/123484205-e3ca6100-d5ff-11eb-8abf-c62e098a4f86.gif)

**Comment by jaywcjlove** [comment]
@rafaelguedes Upgrade `@uiw/react-md-editor@3.4.5`

**Comment by rafaelguedes** [comment]
@jaywcjlove , the problem persists. 
If you refresh the page, it randomly stops working. It's not every time you reload the page, but sometimes, it stops working as expected and it only scrolls one of the sides (as you can see in the gif above).

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/123615496-f0d19500-d837-11eb-9973-a0d3d5740e85.png)
I updated the dependency. You test again.

I tested it and there should be no problems.

@rafaelguedes

**Comment by rafaelguedes** [comment]
I've updated the dependency already. The problem persists.

![Markdown-Editor-for-React-CodeSandbox-_2_](https://user-images.githubusercontent.com/7645688/123619481-2018df80-d801-11eb-8516-167cef591fcb.gif)

**Comment by jaywcjlove** [comment]
@rafaelguedes Upgrade `@uiw/react-md-editor@3.4.6`
