### ISSUE TITLE
Do we have previewOptions with  linkTarget: "_blank" in <MDEditor.Markdown source="value"  />

### ISSUE THREAD

**Issue by IntelligaiaVivek** [uiwjs/react-md-editor#211]
Not able to open url on new tab while using <MDEditor.Markdown> for preview,
can we have url linkTarget on new tab in this preview ?
 
<MDEditor.Markdown 
previewOptions={{
                            linkTarget: "_blank"
                             }}
source={value} />

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/0b26cd443a8359e9b8a4e42364f989cee82a844b/website/Exmaple.tsx#L26-L28

@IntelligaiaVivek 

```jsx
<MDEditor.Markdown
  source={value}
  linkTarget="_blank"
  // previewOptions={{
  //   linkTarget: "_blank"
  // }}
/>
```

**Comment by jaywcjlove** [comment]
@IntelligaiaVivek https://codesandbox.io/s/markdown-editor-for-react-izdd6?from-embed=&file=/index.js:951-1106

**Comment by IntelligaiaVivek** [comment]
@jaywcjlove Awesome Thanks for quick reply :)
