### ISSUE TITLE
Auto resize height based on input

### ISSUE THREAD

**Issue by fgatti675** [uiwjs/react-md-editor#220]
Hi!
First of. all, thank you for the awesome project!
We have currently integrated it into our CMS https://firecms.co/ and it would make total sense for us to have it automatically
resize based on the input.
Something like this:https://stackoverflow.com/questions/454202/creating-a-textarea-with-auto-resize
Thank you :)

**Comment by jaywcjlove** [comment]
@fgatti675 This feature needs to be developed

**Comment by PratikAwaik** [comment]
I second this feature. I tried increase the height dynamically but it was getting ugly.

**Comment by imagine10255** [comment]
Is this feature supported?

**Comment by jaywcjlove** [comment]
@fgatti675 @PratikAwaik @fgatti675 Upgrade `v3.15.0`


```diff
- onHeightChange?: (value?: number, oldValue?: number, state?: ContextStore) => void;
+ onHeightChange?: (value?: CSSProperties['height'], oldValue?: CSSProperties['height'], state?: ContextStore) => void;
```

```diff
- height?: number;
+ height?: CSSProperties['height'];
```

⚠️ `Dragbar` is invalid when **`height`** parameter percentage.

```jsx
<MDEditor
  height="100%"
/>
```
