### ISSUE TITLE
Unable to start project

### ISSUE THREAD

**Issue by undeadfrost** [uiwjs/react-md-editor#256]
The following information is displayed after the installation
Typescript project
<img width="867" alt="run-time" src="https://user-images.githubusercontent.com/24819204/133191188-4d156ecf-7153-4524-9af5-0680651823db.png">

**Comment by jaywcjlove** [comment]
@undeadfrost Example: https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark

**Comment by undeadfrost** [comment]
是按照这种来写的，会提示上面的问题，项目使用ts，需要额外配置webpack吗

**Comment by jaywcjlove** [comment]
@undeadfrost 使用TS写示例： https://codesandbox.io/embed/react-md-editor-custom-toolbars-m2n10?fontsize=14&hidenavigation=1&theme=dark

**Comment by jaywcjlove** [comment]
@undeadfrost 不使用 TS 示例： https://codesandbox.io/embed/react-md-editor-preview-markdown-vrucl?fontsize=14&hidenavigation=1&theme=dark

**Comment by undeadfrost** [comment]
thanks
