### ISSUE TITLE
Cannot edit text on Next.js example

### ISSUE THREAD

**Issue by tatsushim** [uiwjs/react-md-editor#263]
Hi, first of all, thanks for creating the excellent package.

# Problem
- The Next.js example seems not to work correctly since it cannot edit text.
https://codesandbox.io/embed/nextjs-example-react-md-editor-qjhn7?fontsize=14&hidenavigation=1&theme=dark

# Viewer Env
- OS: Mac
- Browser: Google Chrome Version 93.0.4577.82 (Official Build) (x86_64)

**Comment by jaywcjlove** [comment]
@tatsushim I updated the example.

**Comment by tatsushim** [comment]
@jaywcjlove Wonderful. Thanks for the quick update. 
Let me close this issue.
