### ISSUE TITLE
Attempted import error: parse5

### ISSUE THREAD

**Issue by avalero** [uiwjs/react-md-editor#288]
I am getting this error when y try to `yarn run build` a `create-react-app` that uses `react-md-editor`. 

```
Attempted import error: 'parse5/lib/parser/index.js' does not contain a default export (imported as 'Parser').
``` 
This dependency comes from `react-md-editor` package through `/node_modules/hast-util-raw/lib/index.js`

Running in dev mode with `yarn run dev` or `yarn run start` works just right

I am using React 17.

**Comment by jaywcjlove** [comment]
Give me an example to test it?
@avalero

**Comment by avalero** [comment]
Hi @jaywcjlove , I just gave you access to my repository.
Just run `yarn install` on root directory and  `yarn run build` on `packages/cms/`

**Comment by jaywcjlove** [comment]
@avalero I seem to have rejected it. :(

**Comment by avalero** [comment]
Hi @jaywcjlove I invited you again

**Comment by jaywcjlove** [comment]
@avalero The configuration of your `react-app-rewired` tool is wrong.

`packages/cms/config-overrides.js`

```diff
const path  = require('path');

// config-overrides.js
module.exports = function override(config, env) {
  // This line might break with other react-script versions
-  delete config.module.rules[1].oneOf[2].include
+  config.module.rules[1].oneOf[2].include = [
+    config.module.rules[1].oneOf[2].include,
+    path.resolve(process.cwd(), '..', 'common', 'src'),
+  ]
  return config
}
```

**Comment by avalero** [comment]
Amazing @jaywcjlove , thanks!!
