### ISSUE TITLE
使用katex会对原本markdown语法的代码块产生影响，发生错误

### ISSUE THREAD

**Issue by Vang-z** [uiwjs/react-md-editor#291]
直接粘贴该代码不会报错，但是会出现无法渲染的问题
![Snipaste_2021-11-13_17-04-26](https://user-images.githubusercontent.com/44422499/141612934-57322820-8577-48dd-9a2d-66d46a3f4d57.png)

手动输入 ` ```python `，则会直接报错
![Snipaste_2021-11-13_17-04-49](https://user-images.githubusercontent.com/44422499/141613012-2897a60a-3615-4f76-bd9c-d8daaaaaabb0.png)

操作过程均在官网执行，本地项目也出现同样问题

**Comment by jaywcjlove** [comment]
@Vang-z 你使用的什么版本我这里手动输入   ` ```python ` 不会报错

通过 [codesandbox.io](https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark) 将你的实例展示出来？

**Comment by Vang-z** [comment]
> @Vang-z 你使用的什么版本我这里手动输入 `` ```python `` 不会报错
> 
> 通过 [codesandbox.io](https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark) 将你的实例展示出来？

直接在你们的 example 的 katex 实例输入对应的  ` ```python ` 就会直接崩溃
![Snipaste_2021-11-14_12-30-34](https://user-images.githubusercontent.com/44422499/141667592-8522435d-88b9-4103-814d-7892a7eb354a.png)

**Comment by jaywcjlove** [comment]
@Vang-z 实例错误修复完成，并不是包的错误。
