### ISSUE TITLE
Remove some commands from toolbar

### ISSUE THREAD

**Issue by deven96** [uiwjs/react-md-editor#296]
Could it be possible to add a feature to exclude commands such that

```javascript
 import MDEditor, { commands } from '@uiw/react-md-editor';

<MDEditor
   excludeCommands={[
         commands.link,
         commands.image,
       ]}
/>
```

I'd be willing to implement this with some guidance @jaywcjlove  as it would be a better alternative to having to restate all commands

**Comment by jaywcjlove** [comment]
@deven96 I have a better idea.

```ts
commandsFilter?: (command: ICommand) => boolean | ICommand;
```

Use commandsFilter to filter or modify your `commands`.


```jsx
import React from "react";
import MDEditor from '@uiw/react-md-editor';

export default function App() {
  const [value, setValue] = React.useState("**Hello world!!!**");
  return (
    <MDEditor
      value={value}
      onChange={setValue}
      commandsFilter={(cmd) => cmd && /(link|divider)/.test(cmd.name) ? false : cmd}
    />
  );
}
```

**Comment by deven96** [comment]
Perfect

**Comment by pnovales** [comment]
I've tried to hide commands:
`commandsFilter={(cmd) => cmd && /(codeEdit|codeLive|codePreview)/.test(cmd.name) ? false : cmd}`
and just keep the fullscreen, but codeEdit, codeLive and codePreview still visible

**Comment by jaywcjlove** [comment]
@pnovales The problem should be improved.

**Comment by pnovales** [comment]
@jaywcjlove Thanks for the quick response :) 
I've tested it in codesandbox  and the icons still visible
![icons_visible](https://user-images.githubusercontent.com/4325119/144346908-e4a4f8dd-ee93-4d9b-9e68-bea41a1b0122.png)

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/144349656-d9a1f649-db31-4246-9ad6-13d689eede46.png)

@deven96 Example: https://codesandbox.io/embed/react-md-editor-296-ih0wq?fontsize=14&hidenavigation=1&theme=dark

```jsx
import React from "react";
import ReactDOM from "react-dom";
import MDEditor from "@uiw/react-md-editor";
// No import is required in the WebPack.
// import "@uiw/react-md-editor/dist/markdown-editor.css";

const mkdStr = `# Markdown Editor for [React](https://facebook.github.io/react/)
**Hello world!!!**
`;

function App() {
  const [value, setValue] = React.useState(mkdStr);
  return (
    <div className="container">
      <MDEditor
        height={200}
        value={value}
        onChange={setValue}
        commandsFilter={(cmd) => {
          if (/(live|edit)/.test(cmd.name)) {
            return false;
          }
          return cmd;
        }}
      />
    </div>
  );
}
```

**Comment by pnovales** [comment]
@jaywcjlove Great!!! 🚀
