### ISSUE TITLE
How can I extend the default toolbar with a single command?

### ISSUE THREAD

**Issue by cyruscuenca** [uiwjs/react-md-editor#299]
I've read the documentation, and I've gotten my command working, but when I add a custom command, all the default commands are removed. Is there any way to extend the toolbars commands with one more instead of overwriting them? 

If not, where can I find all the default commands so I can add them back?

Thanks!

**Comment by cyruscuenca** [comment]
Oh, and I mean without using extraCommands which overwrites the commands on the right side of the sidebar

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/296

```js
import React from "react";
import MDEditor from '@uiw/react-md-editor';

export default function App() {
  const [value, setValue] = React.useState("**Hello world!!!**");
  return (
    <MDEditor
      value={value}
      onChange={setValue}
      commandsFilter={(cmd) => cmd && /(link|divider)/.test(cmd.name) ? false : cmd}
    />
  );
}
```

There may be a way to help you here.
@cyruscuenca
