### ISSUE TITLE
Improve Bundle Chunking

### ISSUE THREAD

**Issue by kyeotic** [uiwjs/react-md-editor#3]
When bundled with create-react-app default settings this library produces over 400 chunked bundles. They are invidually all small, but total almost 1mb. I don't know what they all are, and they don't all appear to be loaded, but it is quite strange.

It looks like they are mostly from prism. I'm guessing they are individual language highlighting packs. Perhaps there is a way to skip them?

---

This tool is beautiful by the way, thank you for making it. This is easily the nicest markdown editor I've come across

**Comment by kyeotic** [comment]
I might be reading this incorrectly, but it looks like you hardcode the loading of [all languages](https://github.com/uiwjs/react-md-editor/blob/master/src/components/Markdown/langs.ts#L23-L233) from prism. It would be nice to be able to pair this down, perhaps by using the [prism webpack plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs) in the client app and defining the languages as props.

**Comment by jaywcjlove** [comment]
@kyeotic These small JS files are loaded when used, and do not affect the size of the packaged JS.

My application scenario cannot determine which languages ​​to load.

**Comment by kyeotic** [comment]
@jaywcjlove Yes, but the bundles are still present in the deployment, and they still add considerable noise to the build and [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) report. It would be nice if we _could_ whitelist languages so that applications that did know which languages it supported could keep the rest from being bundled. This would be valuable even if the default was to bundle them all.

**Comment by jaywcjlove** [comment]
@kyeotic This requires writing a webpack plugin. This needs to be studied.

**Comment by jaywcjlove** [comment]
@kyeotic We need a plugin like [monaco-editor-webpack-plugin](https://github.com/Microsoft/monaco-editor-webpack-plugin)

**Comment by kyeotic** [comment]
I'm actually having a lot of trouble getting the [prism webpack plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs) to do anything. I tried forking this repo and trimming down the languages, then built with the prism plugin on the lib. I even added the plugin to the app that installed the editor, so that it was running in both places. I get 370+ bundles, which is smaller but not by half as many languages as I removed.

**Comment by jaywcjlove** [comment]
@kyeotic thx! this good idea. I will deal with it when I have time. [@uiwjs/react-markdown-preview](https://github.com/uiwjs/react-markdown-preview)

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-baidu-map/blob/bff63bb0d175487203e2375380f3a76e860d0552/.kktrc.ts#L112-L117

**Comment by ppascualv** [comment]
is there any possible solution without ejecting create-react-app?

**Comment by jaywcjlove** [comment]
@ppascualv https://github.com/kktjs/kkt Override create-react-app webpack configs without ejecting

**Comment by ppascualv** [comment]
Is there any solution for this issue or any workaround without ejecting the app? I was taking a look at your library but I'm not sure how can it solve the issue.

**Comment by jaywcjlove** [comment]
@ppascualv Add webpack config.

https://github.com/uiwjs/react-baidu-map/blob/74459dea893bc696819ae94bd900e01398ee9d1d/.kktrc.ts#L53-L166

**Comment by jaywcjlove** [comment]
@ppascualv Dynamic import is used. Unable to split chunks it.

https://v4.webpack.js.org/plugins/split-chunks-plugin/#split-chunks-example-1

> This configuration can enlarge your initial bundles, it is recommended to use dynamic imports when a module is not immediately needed.

**Comment by guoseven** [comment]
it's not work

> webpack.config.js
```
 optimization: {
      minimize: isEnvProduction,
      minimizer: [
        // This is only used in production mode
        new TerserPlugin({
          terserOptions: {
            parse: {
              // We want terser to parse ecma 8 code. However, we don't want it
              // to apply any minification steps that turns valid ecma 5 code
              // into invalid ecma 5 code. This is why the 'compress' and 'output'
              // sections only apply transformations that are ecma 5 safe
              // https://github.com/facebook/create-react-app/pull/4234
              ecma: 8,
            },
            compress: {
              ecma: 5,
              warnings: false,
              // Disabled because of an issue with Uglify breaking seemingly valid code:
              // https://github.com/facebook/create-react-app/issues/2376
              // Pending further investigation:
              // https://github.com/mishoo/UglifyJS2/issues/2011
              comparisons: false,
              // Disabled because of an issue with Terser breaking valid code:
              // https://github.com/facebook/create-react-app/issues/5250
              // Pending further investigation:
              // https://github.com/terser-js/terser/issues/120
              inline: 2,
            },
            mangle: {
              safari10: true,
            },
            // Added for profiling in devtools
            keep_classnames: isEnvProductionProfile,
            keep_fnames: isEnvProductionProfile,
            output: {
              ecma: 5,
              comments: false,
              // Turned on because emoji and regex is not minified properly using default
              // https://github.com/facebook/create-react-app/issues/2488
              ascii_only: true,
            },
          },
          sourceMap: shouldUseSourceMap,
        }),
        // This is only used in production mode
        new OptimizeCSSAssetsPlugin({
          cssProcessorOptions: {
            parser: safePostCssParser,
            map: shouldUseSourceMap
              ? {
                  // `inline: false` forces the sourcemap to be output into a
                  // separate file
                  inline: false,
                  // `annotation: true` appends the sourceMappingURL to the end of
                  // the css file, helping the browser find the sourcemap
                  annotation: true,
                }
              : false,
          },
          cssProcessorPluginOptions: {
            preset: ['default', { minifyFontValues: { removeQuotes: false } }],
          },
        }),
      ],
      // Automatically split vendor and commons
      // https://twitter.com/wSokra/status/969633336732905474
      // https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366
      splitChunks: {
        // chunks: 'all',
        // name: false,
        cacheGroups: {
          markdown_editor: {
            test: /[\\/]node_modules[\\/]@uiw[\\/]/,
            name: 'vendors-markdown',
            chunks: 'all',
          }
        }
      },
}
```

**Comment by jaywcjlove** [comment]
@guoseven 

https://github.com/uiwjs/react-md-editor/blob/34f61a3bb999fac218de286a3fe53b5758bb7ef9/.kktrc.ts#L41-L45

**Comment by guoseven** [comment]
how to use it

**Comment by jaywcjlove** [comment]
@guoseven Modify webpack configuration. https://webpack.js.org/configuration/optimization/#optimizationsplitchunks

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/586#issuecomment-1788352939
