### ISSUE TITLE
Additional commands for delete all text and add tables

### ISSUE THREAD

**Issue by pnovales** [uiwjs/react-md-editor#303]
Do you have plans to add commands for delete all text (clear) and support md syntax for tables (https://www.markdownguide.org/extended-syntax/#tables) ?  
Or provide examples for these commands ?

This is a great md editor and it would be awesome provide to the users these commands.

**Comment by jaywcjlove** [comment]
@pnovales There is no plan for the time being, you can encapsulate a commands package yourself.
