### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [uiwjs/react-md-editor#308]
Hey there!

I belong to an open source security research community, and a member (@esidate) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jaywcjlove** [comment]
I think this potential security issue can be made public here.
@JamieSlome

**Comment by JamieSlome** [comment]
@jaywcjlove - you can see the report here:

https://huntr.dev/bounties/dea19c2a-ec62-4046-91c9-4c8543ca420c/

Would you like me to go ahead and make the report public? Currently, all maintainers with write permission will be able to view the contents of the report.

**Comment by jaywcjlove** [comment]
@JamieSlome We use [`rehype-sanitize`](https://github.com/rehypejs/rehype-sanitize) to solve it easily.

```jsx
import rehypeSanitize from 'rehype-sanitize'
<MDEditor
  previewOptions={{
    rehypePlugins: [rehypeSanitize]
  }}
/>
```

#249

**Comment by jaywcjlove** [comment]
@JamieSlome thx!

**Comment by JamieSlome** [comment]
@jaywcjlove - you are welcome! If you could mark the report as valid/invalid and confirm the fix, that would be appreciated and the researcher will be awarded a bounty too!
