### ISSUE TITLE
Cursor position not on correct line in textarea

### ISSUE THREAD

**Issue by phillipb** [uiwjs/react-md-editor#312]
When jumping to the end of the textarea via keyboard shortcut (cmd + down arrow), the position of the cursor get's thrown off. I've seen this bug happen another way too, but couldn't reproduce. 

![cursor_position](https://user-images.githubusercontent.com/1482089/145681249-20503806-fd95-4653-8f82-0fd0ef2e9869.gif)

**Comment by phillipb** [comment]
I think this might be related as well: https://github.com/uiwjs/react-md-editor/issues/276. Seems like some issue with the `pre` and the `textarea` line-height maybe.

**Comment by jaywcjlove** [comment]
@phillipb I may have solved this issue.

**Comment by phillipb** [comment]
@jaywcjlove nice! Looks like that that fixed it for me.
