### ISSUE TITLE
Is there an option to hide the live or preview code mode buttons

### ISSUE THREAD

**Issue by kev0960** [uiwjs/react-md-editor#330]
Is there an option to hide the live or preview code mode buttons? 

For example, I want to purely use this as a markdown editor without previewing the markdown. Is there an option to completely hide such buttons in the toolbar?

Thanks

**Comment by jaywcjlove** [comment]
@kev0960 Maybe the following method can help you.

https://github.com/uiwjs/react-md-editor/blob/9cde7c7e5b7f34d8a4359fb986b34538d0229ecc/src/Editor.tsx#L87-L91

- https://github.com/uiwjs/react-md-editor/issues/296 

https://github.com/uiwjs/react-md-editor/blob/9cde7c7e5b7f34d8a4359fb986b34538d0229ecc/website/ExampleCustomToolbar.tsx#L1-L88

**Comment by kev0960** [comment]
Thanks a lot!
