### ISSUE TITLE
Warn users that markdown is not sanitized by default in README.md

### ISSUE THREAD

**Issue by juspky** [uiwjs/react-md-editor#331]
Hi,

I think we should bring more attention to the fact that users are making their application vulnerable to XSS if they don't add rehype-sanitize as a plugin.
Maybe include the example at https://github.com/uiwjs/react-md-editor/blob/master/website/Exmaple.tsx in README.md

**Comment by jaywcjlove** [comment]
Welcome to submit a PR.
@juspky

**Comment by juspky** [comment]
🤝
