### ISSUE TITLE
Code Highlight not working with rehype-sanitize plugin

### ISSUE THREAD

**Issue by mdirshaddev** [uiwjs/react-md-editor#335]
I would first like to thanks for building out this Markdown Editor. It's really worth using.

What I like to mention now is that there is an issue and it is that the code highlighting one. Whenever I am using `rehype-sanitize` plugin the colors are not working.

**Note**: I am not using any CSS files or framework.

![react-md-editor(rehype-sanitize)](https://user-images.githubusercontent.com/68414911/149618665-a415c409-c5b9-4dc3-ba20-971cd213cebd.png)

Do you have any idea to sanitize the data before feeding the string into markdown editor.

Thanking you.

**Comment by mdirshaddev** [comment]
It's working now. Just followed up the person PR who suggested the XSS thing.

**Comment by maertu** [comment]
Have the same problem. Can you elaborate what exactly you did for the highlighting to work in conjunction with rehypeSanitize? To what PR you refer to? thanks

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/a18384fda8ed9885265358dfb801930316f696ab/website/Exmaple.tsx#L31-L49
