### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by H1dEx** [uiwjs/react-md-editor#340]
The final bundle weighs more than 5 MB. I guess, the problem is that it includes minified and regular versions. Dist folder weighs 3.3MB
![image](https://user-images.githubusercontent.com/47990181/152740200-96208d73-ce01-4d97-8922-5bb100c3b002.png)

**Comment by jaywcjlove** [comment]
Include all code highlighting
@H1dEx

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/156701301-07f34692-9288-4cd3-83b6-0b493da33ee1.png)

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/71e1bbe7d42cb35997b2dc64f6fb0761983bb8ff/www/.kktrc.ts#L24-L80

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/586#issuecomment-1788352939
