### ISSUE TITLE
Cannout build production Nextjs

### ISSUE THREAD

**Issue by pascuflow** [uiwjs/react-md-editor#350]
Hi, using Nextjs 12.0.9, building fails with :

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /foo/node_modules/react-markdown/index.js
require() of ES modules is not supported.
require() of /foo/node_modules/react-markdown/index.js from /foo/node_modules/@uiw/react-markdown-preview/lib/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /foo/node_modules/react-markdown/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /foo/node_modules/react-markdown/package.json.
`

If I remove the /foo/node_modules/@uiw/react-markdown-preview/lib/ folder it works, can this be swtiched to esm import syntax?

**Comment by jaywcjlove** [comment]
@pascuflow Provide an example via [codesandbox.io](https://codesandbox.io)?

**Comment by bykof** [comment]
I get the same error

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/154396857-af1d3b12-5a7b-4120-bc59-44b16fc7492c.png)


https://codesandbox.io/embed/nextjs-example-react-md-editor-qjhn7?fontsize=14&hidenavigation=1&theme=dark

I tested this instance and there are no errors. You can provide me with an example.

@bykof @pascuflow 

- https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

**Comment by pascuflow** [comment]
https://codesandbox.io/s/nextjs-example-react-md-editor-forked-3wl4bj?file=/pages/index.js

**Comment by jaywcjlove** [comment]
@pascuflow example: https://codesandbox.io/s/nextjs-example-react-md-editor-forked-89jwvb?file=/pages/index.js

```diff
- import { commands } from "@uiw/react-md-editor";
+ import * as commands from "@uiw/react-md-editor/esm/commands";
```

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/nextjs-example-react-md-editor-forked-89jwvb?fontsize=14&hidenavigation=1&theme=dark

```diff
import * as commands from "@uiw/react-md-editor/lib/commands";
- import { commands } from "@uiw/react-md-editor"
- // or
- import * as commands from "@uiw/react-md-editor/esm/commands";
```
