### ISSUE TITLE
react-md-editor: Nested lists are not showing correct mark character

### ISSUE THREAD

**Issue by Udayendu** [uiwjs/react-md-editor#351]
## Expected list with mark character:
  
![image](https://user-images.githubusercontent.com/1809177/154284351-b3c814cc-6c6e-494f-9888-e20702ab26be.png)

## Actual list with mark character:

![image](https://user-images.githubusercontent.com/1809177/154285072-e8d306a2-49ef-4908-9f03-8c5a546eabdc.png)

**Comment by jaywcjlove** [comment]
@Udayendu Upgrade `v3.9.5`

**Comment by Udayendu** [comment]
> @Udayendu Upgrade `v3.9.5`

Thank you @jaywcjlove . I will do the upgrade and let you know.

**Comment by Udayendu** [comment]
> > @Udayendu Upgrade `v3.9.5`
> 
> Thank you @jaywcjlove . I will do the upgrade and let you know.

Hi @jaywcjlove , I upgraded it to "@uiw/react-md-editor": "^3.9.9" but still its not working. Is it having any dependency ?

**Comment by jaywcjlove** [comment]
@Udayendu Remove dependencies and reinstall
Example: https://codesandbox.io/embed/uiwjs-react-md-editor-issues-351-ep1qb0?fontsize=14&hidenavigation=1&theme=dark
