### ISSUE TITLE
Edit and preview in One Section

### ISSUE THREAD

**Issue by kiran-venugopal** [uiwjs/react-md-editor#352]
Is there any possibility to edit and preview markdown within one section? 

i mean something like this:
![Screenshot (9)](https://user-images.githubusercontent.com/62516337/155762625-dba80281-f2ae-4e3b-aef8-460263d59f33.png)

**Comment by jaywcjlove** [comment]
@kiran-venugopal There is no such possibility.

[`@uiw/react-codemirror`](https://github.com/uiwjs/react-codemirror) maybe possible.

**Comment by kiran-venugopal** [comment]
Thanks
