### ISSUE TITLE
Code block background color changed after upgrading to v3.9.9

### ISSUE THREAD

**Issue by Udayendu** [uiwjs/react-md-editor#354]
- Yesterday to get some fix on the list, I upgraded the `react-md-editor` version to **v3.9.9** which fixed the list issue but now background color for the code block got changed.

### Before upgrade
![image](https://user-images.githubusercontent.com/1809177/156151787-189c085a-0dc3-4bf7-9ee2-88e229ec8683.png)

### After upgrade
![image](https://user-images.githubusercontent.com/1809177/156151482-8fc35345-ccdf-4f29-a58e-72628a7890f1.png)

**Comment by jaywcjlove** [comment]
I confirm this upgrade is correct.

The code block color is the color that plagiarized GitHub displays code blocks.

You can conflict styles to customize.

@Udayendu

**Comment by Udayendu** [comment]
> I confirm this upgrade is correct.
> 
> The code block color is the color that plagiarized GitHub displays code blocks.
> 
> You can conflict styles to customize.
> 
> @Udayendu

Thanks for the update. But this is really strange.
There has not been any change from the code. Just upgraded this particular package and the code block BG is not how it supposed to be.

I just rolled back the code which was having the older version and the code block bg color is looking as expected.

So how to identify what has changed ?

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/compare/v3.9.5...v3.9.9
- https://github.com/uiwjs/react-markdown-preview/compare/v3.4.5...v3.5.1
@Udayendu

**Comment by Udayendu** [comment]
Here is the difference that I can see in the browser:

### On react-md-editor@^3.9.9 and react-markdown-preview@~3.5.0

![image](https://user-images.githubusercontent.com/1809177/156163470-b435b350-da95-4ea5-8b4e-31c05ee08209.png)


### On react-md-editor@^3.8.2 and react-markdown-preview@3.4.1

![image](https://user-images.githubusercontent.com/1809177/156163997-b0663e07-2430-4165-92b0-4695450216f7.png)

**Comment by Udayendu** [comment]
Seems like here is the changes thats breaking the code block color:

Old Working code: https://github.com/uiwjs/react-markdown-preview/blob/v3.4.1/src/styles/markdown.less#L24
New not working code: https://github.com/uiwjs/react-markdown-preview/blob/master/src/styles/markdown.less#L79

Let me know how this can be fixed.

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-markdown-preview/blob/a7dae700b53b741d58f7333584a45044add12e36/src/styles/markdown.less#L73-L81

yes i fixed it, it needs background color.
@Udayendu

**Comment by Udayendu** [comment]
> https://github.com/uiwjs/react-markdown-preview/blob/a7dae700b53b741d58f7333584a45044add12e36/src/styles/markdown.less#L73-L81
> 
> yes i fixed it, it needs background color. @Udayendu

OK. If that's the case then let me see how can I overwrite that in my scss file.

**Comment by Udayendu** [comment]
I was able to fix the code block color in my code itself. So closing this now.
