### ISSUE TITLE
Is the mouse cursor out of position after using full screen mode?

### ISSUE THREAD

**Issue by dhj99116** [uiwjs/react-md-editor#355]
The mouse cursor is out of position after setting an image, especially in full screen mode

**Comment by dhj99116** [comment]
The mouse cursor is not in the right position after setting the image, especially in full screen mode ,
![1646366392(1)](https://user-images.githubusercontent.com/70251319/156696891-4fcdf0ac-d9ed-4205-abc5-2f12dbcd54f6.png)
That's it. The mouse cursor is in the wrong position

**Comment by jaywcjlove** [comment]
@dhj99116 Provide an example via [codesandbox.io](https://codesandbox.io/)?

**Comment by dhj99116** [comment]
@jaywcjlove I didn't find this problem when I tested it at Codesandbox, but the code is the same

**Comment by dhj99116** [comment]
@jaywcjlove  Sorry, I just realized that I set the width of the textarea globally, causing him to force a line break.   I'm sorry.
