### ISSUE TITLE
Cursor line misplaced for long lines in code fragment when not setting language

### ISSUE THREAD

**Issue by peteole** [uiwjs/react-md-editor#357]
Hi, I am having the following issue with the markdown editor:

Let's say I have the following code fragment:
```
TUM: [x,"employee"] => [0.9*x,"research-in-new-topic"]
```

When pasting it into the markdown editor (with the tripple backticks to mark it as code), the editor behaves strangely:
When typing under the code the cursor position is one line above the position where the text you are typing is actually being typed to.
Also special characters are not shown correctly.

This only occurs when no language is set.

Proposal: Set txt as default language

**Comment by peteole** [comment]
https://codesandbox.io/s/react-mde-no-language-bug-6x4tk8?file=/index.js
Here it is. Just make the window width small enough to see it.

**Comment by jaywcjlove** [comment]
@peteole Upgrade `v3.10.1`

**Comment by peteole** [comment]
Thanks, this fixed it!
