### ISSUE TITLE
Dynamic import using next/dynamic throws require.e is not a function error

### ISSUE THREAD

**Issue by pascuflow** [uiwjs/react-md-editor#358]
Hi, 

So I occasionally get this error when I navigate to my page in next js, if I refresh then the page loads fine.

![Screenshot from 2022-03-10 10-41-58](https://user-images.githubusercontent.com/57803063/157698093-914c76eb-7918-495c-84fe-78ac742d913f.png)
![Screenshot from 2022-03-10 10-47-56](https://user-images.githubusercontent.com/57803063/157699279-deb29442-2908-480f-bdd2-b49418f158bd.png)

```
import "@uiw/react-md-editor/markdown-editor.css";
import "@uiw/react-markdown-preview/markdown.css";
import dynamic from "next/dynamic";
import rehypeSanitize from "rehype-sanitize";

const MDEditor = dynamic(
    () => import("@uiw/react-md-editor").then((mod) => mod.default),
    { ssr: false }
);

**Comment by jaywcjlove** [comment]
@pascuflow Provide an example via [codesandbox.io](https://codesandbox.io/)?

Example: https://codesandbox.io/embed/nextjs-example-react-md-editor-qjhn7?fontsize=14&hidenavigation=1&theme=dark

**Comment by pascuflow** [comment]
Cannot seem to reproduce reiliably, going to close.
