### ISSUE TITLE
missing dependency makes import fail with yarn 2

### ISSUE THREAD

**Issue by bradennapier** [uiwjs/react-md-editor#362]
It is important with yarn v2+ that all your dependencies you use are included in your package.json

By default right now this fails due to a requirement for module `rehype-prism-plus`.  That is not in your dependencies.  I am guessing it is depended on by another dependency, which is no longer allowed with yarn v2.  

It would be ideal if y'all could simply add that as a dependency.

Once I did this, everything worked fine with my setup.  Thanks!

For those running into this, had to edit `.yarnrc.yml` and have:

```
packageExtensions:
  "@uiw/react-md-editor@*":
    dependencies:
      "rehype-prism-plus": "*"
```

**Comment by jaywcjlove** [comment]
I'm not using yarn 2 and I'm not sure why the problem occurs.

```bash
@uiw/react-md-editor@3.11.2 
└─┬ @uiw/react-markdown-preview@4.0.5
  └── rehype-prism-plus@1.3.2
```

It doesn't seem to lack `rehype-prism-plus` dependencies.

@bradennapier

**Comment by bradennapier** [comment]
react-md-editor imports it directly, making it a dependency of this package as well as of the markdown preview so it should be in the dependencies.

**Comment by jaywcjlove** [comment]
My understanding is not so. Whether to depend on `rehype-prism-plus` depends on `@uiw/react-markdown-preview`.
@bradennapier 

Previously, we also replaced @mapbox/rehype-prism with the dependency rehype-prism-plus。

- https://github.com/uiwjs/react-markdown-preview/commit/47a681cea4c33334d6f39b1c9e44c46a6390fd9a

**Comment by bradennapier** [comment]
https://github.com/uiwjs/react-md-editor/blob/master/src/components/TextArea/Markdown.tsx#L3

react-md-editor directly depends on the package here, making it a direct dependency of react-md-editor as well.

**Comment by jaywcjlove** [comment]
@bradennapier How should I fix it to support yarn 2?

**Comment by data-enabler** [comment]
I'm also encountering this issue while trying to migrate from npm to pnpm, which treats dependencies in a similarly strict fashion.

Like @bradennapier said, modules directly imported from this library need to be included as a dependency in your package.json file.

**Comment by jaywcjlove** [comment]
@data-enabler This issue has been resolved.

**Comment by doubleforte** [comment]
I believe this commit is actually breaking my jest tests. "SyntaxError: Cannot use import statement outside a module"

The previous version of react-md-editor (3.23.3) did not have a `/node_modules/@uiw/react-markdown-preview/node_modules` directory, but this update (3.23.4) does and it contains `refractor` and `rehype-prism-plus`. If I manually delete that directory, my tests pass. Clearly, that's not the right way to do it. :)

Also of note: `/node_modules/@uiw/react-markdown-preview/package.json` specifies `"rehype-prism-plus": "~1.5.0"` and `/node_modules/@uiw/react-md-editor/package.json` (which I believe is the troublemaker?) specifies `"rehype-prism-plus": "~1.6.1"`

Maybe it's a version mismatch, maybe something else.

I'm on Yarn v1.22.19.

**Comment by jaywcjlove** [comment]
@bradennapier Synchronized the version of `rehype-prism-plus`.

**Comment by doubleforte** [comment]
> @bradennapier Synchronized the version of `rehype-prism-plus`.

Worked great! Thank you!
