### ISSUE TITLE
How can I listen for events when editor height change?

### ISSUE THREAD

**Issue by wangshijun** [uiwjs/react-md-editor#374]
Awesome library!

I looked into the doc, there is only 1 event listener: onChange, which is used for editor content change.

In some cases, I want to persist editor height to localstorage, so user can get a consistent UX when edit across page loads.

So I suggest we add support for `onHeightChange` callback whenever editor height changed

**Comment by jaywcjlove** [comment]
@wangshijun Upgrade `@uiw/react-md-editor@3.12.0`

**Comment by wangshijun** [comment]
@jaywcjlove I tried the latest version, but it seems the height dragbar is broken (I can not change the height anymore), you can reproduce this bug at https://uiwjs.github.io/react-md-editor/

**Comment by jaywcjlove** [comment]
@wangshijun Upgrade `@uiw/react-md-editor@3.12.1`

**Comment by jaywcjlove** [comment]
@wangshijun thx!
