### ISSUE TITLE
Keyboard Enter doesn't take to new line in preview mode

### ISSUE THREAD

**Issue by punithbm** [uiwjs/react-md-editor#375]
When I try to press enter to insert a new line under MD editor it doesn't go to a new line in the preview. If the user presses keyboard enter twice then it's taking to a new line. 
Please find the attached video. Also, let me know if there is any walkaround or any solution to address this. 

https://user-images.githubusercontent.com/13044958/163332838-23a05546-68f7-4ccf-b080-d6e642258f35.mp4

**Comment by jaywcjlove** [comment]
@punithbm This is a feature of [GitHub Flavored Markdown Spec](https://github.github.com/gfm/).



![image](https://user-images.githubusercontent.com/1680273/163337777-027f1837-49a9-4fad-8289-96fc1b9ee349.png)

**Comment by jaywcjlove** [comment]
If you don't like it, you can use the [remark plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md#list-of-plugins) or [rehype plugins](https://github.com/rehypejs/rehype/blob/main/doc/plugins.md#list-of-plugins) to change it.

This may require you to write your own plugin by yourself

@punithbm

**Comment by punithbm** [comment]
Thanks for the response @jaywcjlove  

I was trying to use the remark-breaks plugin but getting an error when trying to add editor props previewOptions for remark plugins. Can you suggest how to user remark breaks plugin with the editor?

**Comment by jaywcjlove** [comment]
@punithbm  Example: https://codesandbox.io/embed/uiwjs-react-md-editor-issues-375-8ihvi6?fontsize=14&hidenavigation=1&theme=dark

```jsx
import React from "react";
import ReactDOM from "react-dom";
import MDEditor from "@uiw/react-md-editor";
import rehypeRewrite from "rehype-rewrite";
// No import is required in the WebPack.
// import "@uiw/react-md-editor/dist/markdown-editor.css";

const mkdStr = `
**Hello world!!!**

header

`;

function App() {
  const [value, setValue] = React.useState(mkdStr);
  return (
    <div className="container">
      <h3>Auto</h3>
      <MDEditor
        height={200}
        value={value}
        onChange={setValue}
        previewOptions={{
          rehypePlugins: [
            [
              rehypeRewrite,
              {
                rewrite: (node, index, parent) => {
                  if (node.type === "text" && node.value === "header") {
                    node.value = "~~~~";
                  }
                }
              }
            ]
          ]
        }}
      />
      <div data-color-mode="light">
        <h3>Light</h3>
        <MDEditor
          height={200}
          value={value}
          onChange={setValue}
          previewOptions={{
            rehypePlugins: [
              [
                rehypeRewrite,
                {
                  rewrite: (node, index, parent) => {
                    if (node.type === "text" && node.value === "header") {
                      node.value = "~~~~";
                    }
                  }
                }
              ]
            ]
          }}
        />
      </div>
      <h3>Auto MDEditor.Markdown</h3>
      <MDEditor.Markdown
        style={{ padding: 15 }}
        source={value}
        linkTarget="_blank"
        rehypePlugins={[
          [
            rehypeRewrite,
            {
              rewrite: (node, index, parent) => {
                if (node.type === "text" && node.value === "header") {
                  node.value = "~~~~";
                }
              }
            }
          ]
        ]}
      />
    </div>
  );
}

ReactDOM.render(<App />, document.getElementById("container"));

```

**Comment by punithbm** [comment]
Thanks a lot @jaywcjlove

**Comment by amolpatel** [comment]
@punithbm What was your solution here? From what I can tell, the `rehypeRewrite` node won't tell you if the user is pressing "enter"

**Comment by kazumi3858** [comment]
Adding `style={{ whiteSpace: 'pre-wrap' }}` works.
```javascript
<MDEditor
  value={value}
  onChange={setValue}
  style={{ whiteSpace: 'pre-wrap' }}
/>
```
