### ISSUE TITLE
TypeError: (0 , cm.visit) is not a function (we can't execute the MDEditor)

### ISSUE THREAD

**Issue by LucasNeevs** [uiwjs/react-md-editor#385]
Good morning. I need help to solve this issue. We're using in our platform, the latest version of this lib (3.12.3) but, before this, we were using the version 3.12.1. In both cases, when we try to enter in a page that have the MDEditor on it, we can see this error:

![image](https://user-images.githubusercontent.com/52714448/168055926-6ea0c9cd-f32c-4493-a3ea-20b2a62673df.png)

Error: **TypeError: (0 , cm.visit) is not a function**

I tried to find this solution on the internet but I found nothing. Could someone help us, please?

**Comment by jaywcjlove** [comment]
A reproducing example can be provided using [codesandbox.io](https://codesandbox.io/).
@LucasNeevs

**Comment by LucasNeevs** [comment]
You can create a free trial account in our platform to see the error.

Free trial account: https://learning.pragmaticworkstraining.com/freeTrial
Correct link to see the error: https://learning.pragmaticworkstraining.com/manageAccount/6

This way is much much better than the codesandbox.

**Comment by jaywcjlove** [comment]
@LucasNeevs I don't know how your code is written.

**Comment by RicardoGaefke** [comment]
Same as [https://github.com/uiwjs/react-md-editor/issues/383](https://github.com/uiwjs/react-md-editor/issues/383).

**Comment by LucasNeevs** [comment]
Yes. Exactly how Ricardo said. But, if it'll be helpful to you to help us, access here: [codesandbox.io - MarkdownEditor](https://codesandbox.io/s/markdown-editor-for-react-forked-wrtz25?file=/index.tsx)

I created this one based on the model that you've created (Ricardo's comment), but using our structure.

**Comment by RicardoGaefke** [comment]
Hey guys,

What we know about this error:

1. The full message error is: `Uncaught TypeError: (0 , unist_util_visit__WEBPACK_IMPORTED_MODULE_1__.visit) is not a function`
2. as we use SSR we put the Editor in a next/dynamic wrapper
3. we were using in our package.json file `"next": "^10.0.5"` and we removed the caret a few weeks ago.

Anyways I created this to reproduce the dynamic import of the editor we use in our platform (with the versions we do have in our actual package.json: [codesandbox](https://codesandbox.io/s/broken-resonance-lj7crb?file=/src/Home.tsx:235-241).

Do you guys have any tip for us?

Thanks a lot for your attention.

**Comment by RicardoGaefke** [comment]
Inspecting the error I've found the build was calling a md-editor dependency which was not automatically installed. So I just run `npm i unist-util-visit` and now it's working pretty fine. You guys can close this if you want to. Thanks a lot.
