### ISSUE TITLE
How to put text on the link below?

### ISSUE THREAD

**Issue by StasSpawn** [uiwjs/react-md-editor#398]
![2022-05-30_143033](https://user-images.githubusercontent.com/56681850/170983460-41edfa17-be71-4bca-9a02-498a8ff525fd.png)

Now you have to click **double enter**, but this will add emply line. 
One **enter** just ignoring.

How can I add text to the very next line, without empty spaces (like Test 1 from right textarea)

**Comment by jaywcjlove** [comment]
@StasSpawn This is parsed by [react-markdown](https://github.com/remarkjs/react-markdown), you can go and ask your question.

**Comment by StasSpawn** [comment]
Sure) Thank you.
