### ISSUE TITLE
Hide preview by default? 

### ISSUE THREAD

**Issue by StasSpawn** [uiwjs/react-md-editor#399]
How can i see from the start only edit section? 
![2022-05-31_150834](https://user-images.githubusercontent.com/56681850/171169794-8548f5ac-81ab-4112-a1ea-4963fb23f5aa.png)

**Comment by jaywcjlove** [comment]
@StasSpawn 

https://github.com/uiwjs/react-md-editor/blob/9f2539ea592938c07a10b8b887a0ba4855312e64/src/Editor.tsx#L52-L54

**Comment by jaywcjlove** [comment]
```ts
export type PreviewType = 'live' | 'edit' | 'preview';
```

@StasSpawn https://codesandbox.io/embed/markdown-editor-for-react-forked-c00ndm?fontsize=14&hidenavigation=1&theme=dark

**Comment by StasSpawn** [comment]
@jaywcjlove Thank you so much, saviour!)
