### ISSUE TITLE
Escaped markdown

### ISSUE THREAD

**Issue by Salah-Akil** [uiwjs/react-md-editor#404]
Hi, I'm trying to access the "escaped" markdown.
For example if I type the following in the markdown editor:

```
*This* is a `const` with a slash \
```

I guess it gets escaped to something like this:

```
*This* is a \`const\` with a slash \\
```

If I'm correct, how do I access/console.log the escaped markdown?

**Comment by jaywcjlove** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/1680273/172661460-438912c1-149f-49f0-a976-c332cf52c39a.png">

I didn't understand your description. Seems to be working fine.

@Salah-Akil

**Comment by Salah-Akil** [comment]
Yes sorry, I just found a solution to my problem, all I had to do is to create an empty object, and add the `value` to it to get the "escape" MD.

![result](https://user-images.githubusercontent.com/61238694/172669147-cb8f3a3a-1d60-4810-8880-3733d9cab80f.png)

@jaywcjlove thank you very much for your work guys!
