### ISSUE TITLE
Implementation of Shortcuts

### ISSUE THREAD

**Issue by foxhard** [uiwjs/react-md-editor#41]
Can you provide an example to extend the component to support custom shortcuts?

I'm looking for something like this:

- italics (cmd + i)
- bold (cmd + b)
- underline (cmd + u)
- strikethrough (cmd + shift + x)
- code: (cmd + j)
- code block (cmd + shift + J)
- ordered list (cmd + shift + O)
- unordened list (cmd + shift + L)
- links (cmd + k)

**Comment by jaywcjlove** [comment]
API design：

```diff
export const bold: ICommand = {
  name: 'bold',
+  shortcuts: 'cmd+i',
  keyCommand: 'bold',
  buttonProps: { 'aria-label': 'Add bold text' },
  icon: (
    <svg role="img" width="12" height="12" viewBox="0 0 384 512">
      ....
    </svg>
  ),
  execute: (state: TextState, api: TextApi) => {},
};
```

**Comment by jaywcjlove** [comment]
### Available modifiers

- `Command` (or `Cmd` for short)
- `Control` (or `Ctrl` for short)
- `CommandOrControl` (or `CmdOrCtrl` for short)
- `Alt`
- `Option`
- `AltGr`
- `Shift`
- `Super`

### Available key codes

- `0` to `9`
- `A` to `Z`
- `a` to `a`

**Comment by s-ashutosh-b** [comment]
> API design：
> 
> ```diff
> export const bold: ICommand = {
>   name: 'bold',
> +  shortcuts: 'cmd+i',
>   keyCommand: 'bold',
>   buttonProps: { 'aria-label': 'Add bold text' },
>   icon: (
>     <svg role="img" width="12" height="12" viewBox="0 0 384 512">
>       ....
>     </svg>
>   ),
>   execute: (state: TextState, api: TextApi) => {},
> };
> ```
> 
> https://github.com/uiwjs/react-md-editor/blob/7a58c1ef8e3a47ffd8fedc5c7e0a0ff8e425b202/src/commands/bold.tsx#L5-L30

Doing this will pop out a Type error, to solve it, 
` shortcut?:string,` would be added in `'./index.ts'` > 
`export type ICommand<T=string>{
...
shortcut?:string,
...
}`

**Comment by jaywcjlove** [comment]
Upgrade `@uiw/react-md-editor@3.0.0-beta.1`

**Available modifiers**

- `ctrlcmd` Command or Control
- `ctrl` Control
- `cmd` Command
- `alt`
- `shift`
