### ISSUE TITLE
Styling Issue within React.

### ISSUE THREAD

**Issue by DaRabus** [uiwjs/react-md-editor#413]
Hey Guys,

I tried a lot of things out and moved the component out of every thinkable style and even tried using the Chrome/Firefox CSS tools, but i just can't get it to a proper fit in any way. the Toolbar is horizontal somehow and also the text field is not changeable in the width...

My other components are MUI based styled so basically nothing which should interfere with

I removed now any styling for showing it.

What do i do wrong..

![image](https://user-images.githubusercontent.com/44967066/176376923-a8f5c850-a04d-4f00-b4c9-e1e76f9247bd.png)
![image](https://user-images.githubusercontent.com/44967066/176376953-5e1394e5-c2c3-4cba-8561-67581cd6cf54.png)
![image](https://user-images.githubusercontent.com/44967066/176377466-e516452d-d535-4417-ade7-fff510f9ec2e.png)

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark

You can give me an example using https://codesandbox.io to reproduce your error.

@DaRabus

**Comment by jaywcjlove** [comment]
I don't understand your question.
@DaRabus

**Comment by jaywcjlove** [comment]
You have to reproduce your problem before I can help you.

**Comment by roshan521** [comment]
@DaRabus  are you now able to use custom css?

**Comment by DaRabus** [comment]
@roshan521 I actually found this alternative which works with the styling.

https://github.com/HarryChen0506/react-markdown-editor-lite

**Comment by roshan521** [comment]
@DaRabus  looks sick bro thanks :+1:

**Comment by jaywcjlove** [comment]
@DaRabus @roshan521 https://github.com/uiwjs/react-markdown-editor

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/f7047fa7089db01dab36e82bc001a68168ad9c48/core/src/index.less#L3-L79

**Comment by jaywcjlove** [comment]
https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-md-editor/file/markdown-editor.css

**Comment by raivatshah** [comment]
Hi @jaywcjlove! 

I'm trying to use this library on my [remix](https://remix.run/) react app. I tried importing the updated CSS file, i.e.`import "@uiw/react-md-editor/dist/mdeditor.css";` but my CSS still does not load well. 

![Screenshot 2023-07-19 at 2 23 32 PM](https://github.com/uiwjs/react-md-editor/assets/29497717/7f21937c-adfa-401e-a6fc-211f6c13d61a)


I'm just trying to setup the basic demo: 

```
import React from "react";
import MDEditor from "@uiw/react-md-editor";
// No import is required in the WebPack.
import "@uiw/react-md-editor/dist/mdeditor.css";

const mkdStr = `
# Markdown Editor

---

**Hello world!!!**

[![](https://avatars.githubusercontent.com/u/1680273?s=80&v=4)](https://avatars.githubusercontent.com/u/1680273?v=4)

\`\`\`javascript
import React from "react";
import ReactDOM from "react-dom";
import MEDitor from '@uiw/react-md-editor';

\`\`\`
`;

export default function LiveEditor() {
  const [value, setValue] = React.useState(mkdStr);
  return (
    <div className="container">
      <h3>Auto</h3>
      <MDEditor height={200} value={value} onChange={(val) => {if (val) setValue(val)}} />
      <h3>Light</h3>
      <div data-color-mode="light">
        <MDEditor height={200} value={value} onChange={(val) => {if (val) setValue(val)}} />
      </div>
      <h3>Light</h3>
      <div data-color-mode="dark">
        <MDEditor height={200} value={value} onChange={(val) => {if (val) setValue(val)}} />
      </div>
    </div>
  );
}
```

Do you have an idea of perhaps how I can fix this?
