### ISSUE TITLE
Image upload along with drag and drop

### ISSUE THREAD

**Issue by roshan521** [uiwjs/react-md-editor#416]
I don't see any props or command to work with images. Can you guide us?

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/83
- https://github.com/uiwjs/react-md-editor/issues/60

This needs to interact with the backend. You need to implement this yourself.
@roshan521

**Comment by roshan521** [comment]
I have made backend api to store img I need to know how to change it into markdown and insert it into text editor

**Comment by jaywcjlove** [comment]
@roshan521 

https://github.com/uiwjs/react-md-editor/blob/8c977d57ee4875ed3149a91875fff98a670e5d59/core/src/commands/hr.tsx#L18-L20

https://github.com/uiwjs/react-md-editor/blob/8c977d57ee4875ed3149a91875fff98a670e5d59/core/src/commands/index.ts#L106-L111

https://github.com/uiwjs/react-md-editor/blob/8c977d57ee4875ed3149a91875fff98a670e5d59/core/src/Editor.tsx#L182
