### ISSUE TITLE
Can css be separated and not introduced into the suite together?

### ISSUE THREAD

**Issue by imagine10255** [uiwjs/react-md-editor#418]
Can css be separated and not introduced into the suite together?

ex: 
```typescript
// modules css
import './index.css';
import 'bear-react-grid/dist/index.css';
import '@bearests/form/dist/index.css';
import 'bear-react-datepicker/dist/index.css';
```

better management style

**Comment by jaywcjlove** [comment]
You can use plugins to strip out css imports. Like this : https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

@imagine10255

**Comment by imagine10255** [comment]
@jaywcjlove Hi, 我不是 nextjs, css 的部分是不是依照自己需要的方式去引入會比較好?

**Comment by jaywcjlove** [comment]
@imagine10255 我的意思是的，如果你想自己引入css，可以使用 [`babel-plugin-transform-remove-imports`](https://github.com/uiwjs/babel-plugin-transform-remove-imports) 类似的插件移除 css 引入，然后你可以自己手动引入，或者自定义。

```js
import "@uiw/react-md-editor/markdown-editor.css";
import "@uiw/react-markdown-preview/markdown.css";
```

**Comment by imagine10255** [comment]
@jaywcjlove 感謝回覆, 知道了
另外我想請問, 為什麼不讓大家一開始就 自己手動引入, 而是需要先移除 後, 再手動引入, 
大部分安裝到的套件的使用經驗都是這樣(沒手動引入就沒有CSS樣式)

**Comment by jaywcjlove** [comment]
@imagine10255 我一开始使用的工具，就不需要 手动引入，如 [create-react-app](https://github.com/facebook/create-react-app) 和我自己搞的工具 [kkt](https://github.com/kktjs/kkt) 也不需要，。公司内部项目全部都不需要手动引入 css。如果改了 所有项目都需要修改。这很麻烦。

**Comment by imagine10255** [comment]
@jaywcjlove 了解。不過 create-react-app 是需要自己引入的吧?

https://codesandbox.io/s/trusting-jepsen-r52lgq?file=/src/App.js

<img width="1375" alt="CleanShot 2022-07-27 at 10 28 44@2x" src="https://user-images.githubusercontent.com/5771353/181147762-f1889f13-5126-4a2c-951d-1660cf977c9c.png">

**Comment by jaywcjlove** [comment]
@imagine10255 https://codesandbox.io/s/uiwjs-react-md-editor-issues-418-vyrtdm?file=/src/App.js:72-92

看它不需要引入包中的样式，就可以加载样式

**Comment by imagine10255** [comment]
@jaywcjlove 了解 感謝你
