### ISSUE TITLE
Editor reloads with state change in Next JS

### ISSUE THREAD

**Issue by dukesx** [uiwjs/react-md-editor#422]
I am using NextJS@latest i.e 12.2 with React 18 and above. I am loading it with next/dynamic but it seems that the moment i change the state (edit inside editor), the editor reloads itself (re-renders). This means that if i enter a letter, the cursor looses focus and i can only type ONE letter at a time. 

Not sure what is going on but from what i know, this is a persistent issue with editors that are not compatible with SSR apis. If i use TinyMCE or any other, they seem to work flawlessly. Only way to make it work is through useRef since it does not cause re-render.

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/uiwjs-react-md-editor-issues-421-w1rryo?fontsize=14&hidenavigation=1&theme=dark

@dukesx Can you give me a reproducible example?

**Comment by dukesx** [comment]
Okay , it seems that issue was with my side. It just randomly started working correctly. I will close this issue.
