### ISSUE TITLE
Editor wrapped in `pre`?

### ISSUE THREAD

**Issue by amolpatel** [uiwjs/react-md-editor#424]
For some reason, the editor is wrapped in a pre and I can't find anywhere to disable that in the props. I'm using NextJS and tailwind. I followed the instructions on how to install using Next. Any help would be appreciated!

![CleanShot 2022-08-08 at 14 00 21@2x](https://user-images.githubusercontent.com/6493663/183483456-5b45efef-854a-40e2-8500-58729f7f7abd.png)

Rendered HTML:
![CleanShot 2022-08-08 at 14 03 34@2x](https://user-images.githubusercontent.com/6493663/183483827-fe4f3a66-776e-4f87-9694-331d765e13d2.png)

React code:
```typescript
import "@uiw/react-markdown-preview/markdown.css";
import "@uiw/react-md-editor/markdown-editor.css";
import dynamic from "next/dynamic";
import React from "react";

interface Props {
  value: string;
  onChange: (value: string) => void;
}

const MDEditor = dynamic(() => import("@uiw/react-md-editor"), { ssr: false });

export default function MarkdownEditor({ value, onChange }: Props): JSX.Element {
  return (
    <div className="container">
      <MDEditor value={value} onChange={(text) => onChange(text ?? "")} />
    </div>
  );```

**Comment by dukesx** [comment]
@amolpatel do you have any issue with editor reloading on state change ?

**Comment by amolpatel** [comment]
@dukesx nope, I don't think so

**Comment by dukesx** [comment]
@amolpatel strangely , whenever i enter a value inside the editor, the damn thing just resets itself, like the state, its like the state change triggers it to reset for some reason

**Comment by nickscamara** [comment]
Happening to me as well. @amolpatel what was the fix?

**Comment by amolpatel** [comment]
@nickscamara You just need to re-render the `textarea`:

```javascript
<MDEditor
    value={value}
    onChange={(text) => onChange(text ?? "")}
    components={{
      textarea: (props) => {
        return (
          // @ts-ignore
          <textarea {...props} />
        );
      },
    }}
  />
```

**Comment by nickscamara** [comment]
@amolpatel Thank you very much. That and upgrading to the latest version fixed.
