### ISSUE TITLE
Editor Font

### ISSUE THREAD

**Issue by Clay-Ferguson** [uiwjs/react-md-editor#425]
I couldn't find a way to set the font for the editor, and in the `less` file I found it seems to be hard-coded. Any suggestions? Should I just figure out which class to override, by inspecting the dom, and try overriding that? Maybe this is a dumb question and we're supposed to just override styles as needed, but I was unsure.

**Comment by jaywcjlove** [comment]
@Clay-Ferguson This can cause text ghosting problems.

https://github.com/uiwjs/react-md-editor/issues/276#issue-1015183157

**Comment by Clay-Ferguson** [comment]
I just need a **bigger** font, so text is easier to read. It's ok if the component itself still chooses the actual font, but I just need it larger. I prefer a fixed width font too, but that's just my preference.

Perhaps some font style settings like this...if you can't let the actual font be styled by users.

```
FontStyle = FIXED || VARIABLE
FontSize = SMALL || MEDIUM || LARGE
```

**Comment by Clay-Ferguson** [comment]
That works perfectly! Doesn't support fixed width font, but basically solves my primary need. Thank you!
