### ISSUE TITLE
Horizontal line disappears when container overflows.

### ISSUE THREAD

**Issue by arklian** [uiwjs/react-md-editor#426]
Due to the display flex added in [this pr](https://github.com/uiwjs/react-md-editor/commit/aba69a33109c946392781521224a35a13252f696) the horizontal lines shrink and then disappear if the container has too much text. 

Repro: https://codesandbox.io/s/markdown-editor-for-react-forked-2qq959?file=/index.js
Expand the container to have the hr's appear again.

**Comment by jaywcjlove** [comment]
@arklian I fixed this issue. You need to remove node_modules and reinstall dependencies. `@uiw/react-markdown-preview` dependencies will be automatically upgraded to `v4.0.24`
