### ISSUE TITLE
Toolbar fixed height breaks if min width is too low

### ISSUE THREAD

**Issue by arklian** [uiwjs/react-md-editor#427]
If there are too many toolbar icons for the width, the fixed 29 height doesn't fit all of them.
![image](https://user-images.githubusercontent.com/37193658/184042556-bc4e742b-2da1-403d-980b-7d8fa790f611.png)

**Comment by jaywcjlove** [comment]
@arklian  Upgrade `v3.17.2`

**Comment by jaywcjlove** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/1680273/184094562-641f8fec-399c-4b21-8cb6-df0c2f76f284.png">

https://codesandbox.io/embed/markdown-editor-for-react-uiwjs-react-md-editor-issues-427-bs9stw?fontsize=14&hidenavigation=1&theme=dark

@arklian

**Comment by arklian** [comment]
Thank for the quick update!
