### ISSUE TITLE
Formatting with Tailwind & Remix

### ISSUE THREAD

**Issue by InTheCloudDan** [uiwjs/react-md-editor#431]
Thanks for the amazing library, I'm trying to get it configured but I'm not sure if because of SSR that the `**Hello world!!!**` string is constantly showing above the `textarea`? I've tried using different `preview` settings none of them seem to affect that line https://github.com/uiwjs/react-md-editor/blob/71e1bbe7d42cb35997b2dc64f6fb0761983bb8ff/core/src/components/TextArea/Markdown.tsx#L34-L37 unless the whole textarea is hidden. 

Also Is there also any guidance for how to get the toolbar showing normally in remix with tailwind?
 
<img width="197" alt="image" src="https://user-images.githubusercontent.com/10308834/187320865-24a99c54-b1d2-4d81-81f0-977bc5e082dd.png">

**Comment by jaywcjlove** [comment]
@InTheCloudDan Can an instance be provided using [codesandbox.io](https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark) ?

**Comment by InTheCloudDan** [comment]
@jaywcjlove I'm working on it, I have a basic remix app running in the sandbox now, but when I go to add the  ESM files `serverDependenciesToBundle` it tells me `Upgrade Required`, any idea how to get around that? https://codesandbox.io/s/codesandbox-sse-example-forked-1vvl7z?file=/remix.config.js

I think it's due to `/build/index.js is larger than maximum allowed file size (1457058 > 524288), not synchronizing`

**Comment by jaywcjlove** [comment]
- https://github.com/remix-run/remix/issues/185
- https://github.com/remix-run/remix/issues/2469
- https://github.com/remix-run/remix/issues/108
@InTheCloudDan

**Comment by cliffordfajardo** [comment]
> I think it's due to /build/index.js is larger than maximum allowed file size (1457058 > 524288), not synchronizing

I think it's due to /build/index.js is larger than maximum allowed file size (1457058 > 524288), not synchronizing
@InTheCloudDan - i think the remix template is out of date. You'll need to add a .gitignore file to resolve the problem. More details on the error here
https://github.com/codesandbox/codesandbox-client/issues/6786

**Comment by jaywcjlove** [comment]
The component style is not loaded. I have seen many people encounter this problem with remix.

**Comment by InTheCloudDan** [comment]
thanks @jaywcjlove and @cliffordfajardo I'll follow along on those remix issues.
