### ISSUE TITLE
Input form lose focus every time when typing a character

### ISSUE THREAD

**Issue by KirschX** [uiwjs/react-md-editor#436]
///component/MdEditor
```jsx
const MdEditor = () => {
  const MDEditor = dynamic(() => import("@uiw/react-md-editor"), {
    ssr: false,
  });

  const [md, setMd] = useState<string | undefined>("# Hello World");

  let mdRef = useRef("");

  return <MDEditor value={md} onChange={setMd} />;
};

export default MdEditor;`


```

//main

```jsx
<>
(some react-hook-form library component)
<>
 <div>
        <MdEditor />
</div>
```

Problem)
Every time I type 1 character, input field lose focus.
I also put it on parent(main) component but problem happend same again.
I don't think it's related with other libraries.
I think it is realated with rerendering or something, but can't find out how to handle this problem.

What is them problem and what can I do in this situation??

**Comment by jaywcjlove** [comment]
@KirschX https://codesandbox.io/s/markdown-editor-for-react-izdd6?from-embed

I can't reproduce your problem, can you give me an example that reproduces this error.

**Comment by KirschX** [comment]
@jaywcjlove Oh, sorry. I just solved the problem, I was stupid. I should have imported the the module outside of the function component.
