### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by JEMasonMedia** [uiwjs/react-md-editor#437]
For whatever reason, I am getting the below parse warning. It has nothing to do with my code as it only appears when I "import MDEditor from '@uiw/react-md-editor'" The library still seems to work fine, but I am not sure what to do about these major warnings.

> Failed to parse source map from 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\compile.ts' file: Error: ENOENT: no such file or directory, open 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\compile.ts'

> Failed to parse source map from 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\index.ts' file: Error: ENOENT: no such file or directory, open 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\index.ts'

> Failed to parse source map from 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\parse.ts' file: Error: ENOENT: no such file or directory, open 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\parse.ts'

**Comment by JEMasonMedia** [comment]
More info:

> WARNING in ./node_modules/nth-check/lib/esm/compile.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\compile.ts' file: Error: ENOENT: no such file or directory, open 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\compile.ts'

> WARNING in ./node_modules/nth-check/lib/esm/index.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\index.ts' file: Error: ENOENT: no such file or directory, open 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\index.ts'

> WARNING in ./node_modules/nth-check/lib/esm/parse.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\parse.ts' file: Error: ENOENT: no such file or directory, open 'G:\Projects\folder\current\node_modules\nth-check\lib\esm\https:\raw.githubusercontent.com\fb55\nth-check\639fd2a4000b69f82350aad8c34cb43f77e483ba\src\parse.ts'

**Comment by jaywcjlove** [comment]
<img width="767" alt="image" src="https://user-images.githubusercontent.com/1680273/192105453-9639d8d6-b179-423a-8865-86c4f444e01d.png">

https://www.npmjs.com/package/source-map-loader#user-content-examples

Some popular packages do not provide sourcemap files, which is normal, and you can configure to ignore warnings for these packages. @JEMasonMedia 

https://webpack.js.org/configuration/other-options/#ignorewarnings

**Comment by JEMasonMedia** [comment]
I must be missing something. I just installed the library and set up the config file, but nothing changed once I restarted the app. I used create-react-app to bootstrap my app. Could you possibly provide a little more info please?

**Comment by jaywcjlove** [comment]
@JEMasonMedia I don't know why you have this error, I can't reproduce your error.

**Comment by JEMasonMedia** [comment]
How to reproduce:

```
npx create-react-app .
npm i @uiw/react-md-editor
```

import the library into App.js:
`import MDEditor from '@uiw/react-md-editor'`

`npm start`

Those warnings will appear in the console.

**Comment by jaywcjlove** [comment]
@JEMasonMedia  https://codesandbox.io/embed/uiwjs-react-md-editor-issues-437-0sx4ju?fontsize=14&hidenavigation=1&theme=dark

**Comment by jaywcjlove** [comment]
I reproduced this problem.

- https://github.com/kktjs/kkt/issues/325

I've been using my own tools. This issue was ignored.

@JEMasonMedia

**Comment by jaywcjlove** [comment]
- https://github.com/facebook/create-react-app/pull/11752

**Comment by jaywcjlove** [comment]
- https://github.com/webpack-contrib/source-map-loader/pull/117

**Comment by jaywcjlove** [comment]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/1680273/192111017-3ae55316-6363-4a6f-a45d-9bd94b4f3368.png">

```diff
"scripts": {
-  "start": "react-scripts start",
+  "start": "GENERATE_SOURCEMAP=false react-scripts start",
  "build": "react-scripts build",
  "test": "react-scripts test",
  "eject": "react-scripts eject"
},
```

@JEMasonMedia

**Comment by jaywcjlove** [comment]
It was fixed by adding `GENERATE_SOURCEMAP=false` to the `.env` file. 

@JEMasonMedia

**Comment by JEMasonMedia** [comment]
'GENERATE_SOURCEMAP' is not recognized as an internal or external command,
operable program or batch file.

.env?

**Comment by JEMasonMedia** [comment]
"scripts": {
    "start": "GENERATE_SOURCEMAP=false react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },

**Comment by jaywcjlove** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/1680273/192111213-143123ed-44f0-469d-b5a6-b9b5f6ff876c.png">

@JEMasonMedia

**Comment by JEMasonMedia** [comment]
Finally googled what you were saying and got the .env workaround to work. Thank you for helping me out!

**Comment by jaywcjlove** [comment]
If you are running on Windows, you need to use the compatible tool [`cross-env`](https://www.npmjs.com/package/cross-env)

```bash
npm install --save-dev cross-env
```


```js
"start": "cross-env GENERATE_SOURCEMAP=false react-scripts start",
```

@JEMasonMedia Of course, the way to use `.evn` is not needed.

**Comment by JEMasonMedia** [comment]
The .env worked on its own in windows 11. Thank you very much for your help.
