### ISSUE TITLE
Support Next.js

### ISSUE THREAD

**Issue by jaywcjlove** [uiwjs/react-md-editor#446]
I created a nextjs package [`next-remove-imports`](https://www.npmjs.com/package/next-remove-imports) to solve the problem.

Example: https://codesandbox.io/s/nextjs-example-react-md-editor-qjhn7?file=/pages/index.js  
Example: [@uiwjs/next-remove-imports/example](https://github.com/uiwjs/next-remove-imports/tree/main/example)  
Example: https://next-remove-imports-example.vercel.app

[![Open in CodeSandbox](https://img.shields.io/badge/Open%20in-CodeSandbox-blue?logo=codesandbox)](https://codesandbox.io/embed/nextjs-example-react-md-editor-qjhn7?fontsize=14&hidenavigation=1&theme=dark) [![Open in StackBlitz](https://img.shields.io/badge/Open%20In-StackBlitz-green)](https://stackblitz.com/edit/nextjs-react-md-editor?embed=1&file=pages/index.js&hideExplorer=1&hideNavigation=1&theme=dark)

```bash
npm i @uiw/react-md-editor@v3.6.0
npm i next-remove-imports
```

```js
// next.config.js
const removeImports = require("next-remove-imports")();

module.exports = removeImports({
  // ✅  options...
});
```

```jsx
import "@uiw/react-md-editor/markdown-editor.css";
import "@uiw/react-markdown-preview/markdown.css";
import dynamic from "next/dynamic";
import { useState } from "react";

const MDEditor = dynamic(
  () => import("@uiw/react-md-editor").then((mod) => mod.default),
  { ssr: false }
);
const EditerMarkdown = dynamic(
  () =>
    import("@uiw/react-md-editor").then((mod) => {
      return mod.default.Markdown;
    }),
  { ssr: false }
);

function HomePage() {
  const [value, setValue] = useState("**Hello world!!!**");
  return (
    <div data-color-mode="dark">
      <MDEditor value={value} onChange={setValue} />
      <div style={{ paddingTop: 50 }}>
          <EditerMarkdown source={value} />
      </div>
    </div>
  );
}

export default HomePage;
```

----

- https://github.com/uiwjs/react-md-editor/issues/350#issuecomment-1042629304

```diff
import * as commands from "@uiw/react-md-editor/lib/commands";
- import { commands } from "@uiw/react-md-editor"
- // or
- import * as commands from "@uiw/react-md-editor/esm/commands";
```

example: https://codesandbox.io/s/nextjs-example-react-md-editor-forked-89jwvb?file=/pages/index.js

---

```diff
import { MDEditorProps } from '@uiw/react-md-editor';
import * as commands from '@uiw/react-md-editor/esm/commands';

+ const MDEditor = dynamic<MDEditorProps>(() => import('@uiw/react-md-editor'), {
+   ssr: false,
+ });

function HomePage() {
-  const MDEditor = dynamic<MDEditorProps>(() => import('@uiw/react-md-editor'), {
-    ssr: false,
-  });
  return (
    <div>
      <MDEditor
         value="**Hello world!!!**"
         commands={[
           commands.bold,
           commands.italic,
         ]}
      />
    </div>
  );
}
```

----

- https://github.com/vercel/next.js/issues/9607
- #438  
- #224
- #350
- #422 

----

_Originally posted by @jaywcjlove in https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341_

**Comment by preetpatel** [comment]
What worked for me (Next.js version 13.4.3) is inside your next.config.mjs add the following to your config:

```
experimental: {
    esmExternals: 'loose',
  },
```

**Comment by alexdanilowicz** [comment]
@preetpatel that seems to only work _sometimes_. With that change, I am to get it to load, but every 5 minutes or so, it seems to crash again. 

```bash
- error Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/code/node_modules/@uiw/react-markdown-preview/node_modules/react-markdown/index.js from /Users/zeus/code//node_modules/@uiw/react-markdown-preview/lib/index.js not supported.
Instead change the require of /Users/zeus/code/node_modules/@uiw/react-markdown-preview/node_modules/react-markdown/index.js in /Users/zeus/code/node_modules/@uiw/react-markdown-preview/lib/index.js to a dynamic import() which is available in all CommonJS modules.
```

Is simply adding 

```
experimental: {
    esmExternals: 'loose',
  },
 ```
 stable for you?
 
 I tried 
 ```// next.config.js
const removeImports = require("next-remove-imports")();

module.exports = removeImports({
  // ✅  options...
});
```

But did not have any luck.

**Comment by alexdanilowicz** [comment]
I get `Error: Cannot find module 'babel-plugin-transform-remove-imports'` when trying to use the next-remove-imports package

**Comment by Producdevity** [comment]
@aploon 
> in general react-md-editor package dont work correctly with nextjs.

Can you elaborate on this? why does it not work correctly? what do you mean by "correctly"?
