### ISSUE TITLE
type of height is string. 

### ISSUE THREAD

**Issue by 0xMALVEE** [uiwjs/react-md-editor#469]
type of the prop height is a string. 
but it should be a number.
when using typescript it gives an error.
fix it

**Comment by jaywcjlove** [comment]
@0xMALVEE Upgrade `v3.20.2`

**Comment by 0xMALVEE** [comment]
thank you for fixing it

**Comment by dkryaklin** [comment]
@jaywcjlove now I am getting error when passing percentage string 🤔

**Comment by thomasdohyunkim** [comment]
Agreed, there should be a string option to pass in a percentage.

**Comment by TimAufdemKampe** [comment]
Yes the height prop should be typed as string | number to also allow percentage values

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/ae53d0db6d322766b8f8d9aeaaf70e1cc75671bb/core/src/Editor.tsx#L35-L38

@0xMALVEE @thomasdohyunkim @TimAufdemKampe  

After testing the original type declaration is allowed to pass numbers and strings, so...
