### ISSUE TITLE
Error when specifying "100%" to height

### ISSUE THREAD

**Issue by ngocdaothanh** [uiwjs/react-md-editor#47]
See: https://github.com/uiwjs/react-md-editor/blob/master/src/MDEditor.tsx

Type of `height`:
`height?: React.CSSProperties['height']`

But when specifying `"100%"`, there's error:
```
index.js:1 Warning: `NaN` is an invalid value for the `height` css style property.
    in div (created by MDEditor)
    in div (created by MDEditor)
```

I think at this line:
```
style={{ height: this.state.fullscreen ? 'calc(100% - 29px)' : (this.state.height as number) - 29 }}
```

If we change to below, the error can be fixed:
```
style={{ height: this.state.fullscreen ? 'calc(100% - 29px)' : `calc(${this.state.height} - 29px` }}
```

**Comment by jaywcjlove** [comment]
@ngocdaothanh This modification destroys the style.

**Comment by SillyFreak** [comment]
Is this fixed on master, or is there a style issue left? If it's fixed, would it be possible to do a release?

If not, I tried to work around this by updating the `height` prop when the container's height changes, but it seems the prop is only read once on initialization. After that, the drag bar can control the height, but not the prop. Would it be possible to use the `height` prop for updating the component?

**Comment by jaywcjlove** [comment]
Published.
