### ISSUE TITLE
Text character alignment issue

### ISSUE THREAD

**Issue by Wyatt-SG** [uiwjs/react-md-editor#475]
After adding the editor to my site the text seems to be in a different place and the cursor thinks it is:
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/42128929/214094695-a947e31f-4c87-40bd-b867-9aff5dc330b8.png">

Additional context: this was fixed by disabling syntax highlighting- syntax highlighting is most likely causing the issue

**Comment by MADEiN83** [comment]
Hi,
I'm having the same issue on my side. I confirm your workaround works.

`highlightEnable={false}`

Thanks!

**Comment by jaywcjlove** [comment]
@MADEiN83 @Wyatt-SG  Style conflicts.

- #279
- #173
- #114
- #63
