### ISSUE TITLE
Editor text overflow and result into not correct cursor position. Firefox v109.0 

### ISSUE THREAD

**Issue by faisalamin9696** [uiwjs/react-md-editor#476]
Hi, the text overflow from the defined height, and after scrolling it the cursor position gets some padding. As shown here

Issue occurred when I set 
        font-family: "Microsoft YaHei", Helvetica, "Meiryo UI", "Malgun Gothic", "Segoe UI", "Trebuchet MS", "Monaco", monospace, Tahoma, STXihei, "华文细黑", STHeiti, "Helvetica Neue", "Droid Sans", "wenquanyi micro hei", FreeSans, Arimo, Arial, SimSun, "宋体", Heiti, "黑体", sans-serif;

![image](https://user-images.githubusercontent.com/53206866/214517357-51aba655-86ed-4249-8c8e-d42d1dbb52aa.png)

![image](https://user-images.githubusercontent.com/53206866/214517642-e6f07b0e-2498-42f6-a25c-46c2415b97c3.png)

 I am using the latest version of @uiw/react-md-editor": "^3.20.2"
react 18.2.0

**Comment by rizkianakbar** [comment]
Can someone help to solve this problem? I also experienced the same thing.

**Comment by jaywcjlove** [comment]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/1680273/219534969-d6809689-2fca-447d-a2d9-76b693eb004b.png">

@faisalamin9696 @rizkianakbar 

This is definitely a style conflict, overriding the default line height

https://github.com/uiwjs/react-md-editor/blob/7c85886389e7e94b6555ee8a05a0080e7528438c/core/src/components/TextArea/index.less#L19
