### ISSUE TITLE
Component import error

### ISSUE THREAD

**Issue by Ibadichan** [uiwjs/react-md-editor#488]
Hi! Thanks for the library. I am using loadable-components + webpack to load the `react-md-editor`.
Please can you help me understand how to solve this error?
<img width="1728" alt="Screenshot 2023-03-09 at 14 02 17" src="https://user-images.githubusercontent.com/26125121/224017380-13873eaa-146b-4c54-9570-5edfebd1eaea.png">

**Comment by jaywcjlove** [comment]
Please use [codesandbox.io](https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark) to provide examples

@Ibadichan
