### ISSUE TITLE
Some elements are not displaying correctly in textarea

### ISSUE THREAD

**Issue by ezeamin** [uiwjs/react-md-editor#496]
![image](https://user-images.githubusercontent.com/82628932/228297075-51e6052e-06fe-403a-807f-c46b609a835d.png)

Some elements like image, text in bold, italics, are not displaying in the textarea, unless those texts are selected. 

![image](https://user-images.githubusercontent.com/82628932/228297501-f1fcc3d4-95ca-42de-9fde-958d1e60a064.png)

![image](https://user-images.githubusercontent.com/82628932/228297971-ab21cce3-0883-4c75-a899-1fb92a619c2f.png)

I'm only using rehype-sanitize as plugin, but the error existed since i first installed the library. The mentioned classname does nothing but animate the component.

**Comment by jaywcjlove** [comment]
If you can provide me with an example through [codesandbox.io](https://codesandbox.io/embed/markdown-editor-for-react-izdd6?fontsize=14&hidenavigation=1&theme=dark), I can help you troubleshoot. It may be due to a style conflict. @ezeamin

**Comment by ezeamin** [comment]
Sure! Here it is.

[CodeSandbox](https://codesandbox.io/p/github/ezeamin/avisos-psae-fe/test?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A16%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A16%2C%22startLineNumber%22%3A3%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522clfuzqo9r0001g6ehgmstgj68%2522%252C%2522openFiles%2522%253A%255B%2522%252Findex.html%2522%252C%2522%252Fsrc%252Fcomponents%252FFooter.tsx%2522%252C%2522%252Fpublic%252Findex.css%2522%255D%252C%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfuzsq1c00fu356lgvp3732m%2522%253A%257B%2522key%2522%253A%2522clfuzsq1c00fu356lgvp3732m%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522clfv0dey100kh356l37to8o3g%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clfv0ddjm00cn356lxjgqbql3%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%252C%2522clfv08b7v0akr356ldeukurhh%2522%253A%257B%2522key%2522%253A%2522clfv08b7v0akr356ldeukurhh%2522%252C%2522devtools%2522%253A%255B%255D%252C%2522name%2522%253A%2522New%2522%257D%252C%2522clfv0jpev03bs356lega5orj0%2522%253A%257B%2522key%2522%253A%2522clfv0jpev03bs356lega5orj0%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clfv0jr7l0005g4gk93k32ht3%2522%252C%2522key%2522%253A%2522clfv0jr4n03dh356lva35g43j%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%252C%2522name%2522%253A%2522Terminal%2522%257D%257D%252C%2522currentSpace%2522%253A%2522clfv0jpev03bs356lega5orj0%2522%252C%2522spacesOrder%2522%253A%255B%2522clfuzsq1c00fu356lgvp3732m%2522%252C%2522clfv08b7v0akr356ldeukurhh%2522%252C%2522clfv0jpev03bs356lega5orj0%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D)

The problem is when setting a display: flex in a container above the editor. In this case, i use it over all the page content (set in App.tsx with the class "content") to make sure the footer stays on the lower end of the screen. I included the styling library I use (MUI / Emotion) to make sure you get the whole context in which I'm working in.

I really appreciate your time.

**Comment by jaywcjlove** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1680273/229423918-9b8a5c6e-ce2d-4b9b-a905-14d987bdc654.png">

@ezeamin

**Comment by ezeamin** [comment]
@jaywcjlove I'm sorry, what did you try to send me? It says "Page not found"

**Comment by ezeamin** [comment]
@jaywcjlove check again please. The error was due a visibility config

**Comment by jaywcjlove** [comment]
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/1680273/229530037-ad83e2a8-8513-433f-9a6a-2ee93d1aea62.png">

style conflict @ezeamin
