### ISSUE TITLE
Release 3.20.6 wasn't successful

### ISSUE THREAD

**Issue by Exmirai** [uiwjs/react-md-editor#500]
![image](https://user-images.githubusercontent.com/6436703/229439930-13765170-5a7b-4334-a5fe-712c84822c6d.png)
https://github.com/uiwjs/react-md-editor/actions/runs/4593480016/jobs/8111445600#step:22:235

**Comment by Exmirai** [comment]
Seems like it still failing
https://github.com/uiwjs/react-md-editor/actions/runs/4594817123/jobs/8114321229#step:22:241

**Comment by jaywcjlove** [comment]
@Exmirai Released successfully!
