### ISSUE TITLE
How to add coloured text?

### ISSUE THREAD

**Issue by iamvaibhavrai** [uiwjs/react-md-editor#505]
I have tried wrapping the text inside the `span` tag with colour in style but it didn't work. 
<span style="color:red">text</span>

Is there any other way to apply text colour?

**Comment by jaywcjlove** [comment]
i don't understand your description

@iamvaibhavrai 

can you give me an example

**Comment by iamvaibhavrai** [comment]
Hey @jaywcjlove, thanks for the reply. Github trimmed the code. Adding it again.

`<span style="color:red">Red colored text</span>`

I tried this to change the color of the text.

**Comment by iamvaibhavrai** [comment]
<span style={{color:"red"}}>Red colored text</span>

This worked
