### ISSUE TITLE
Ability to create custom component

### ISSUE THREAD

**Issue by SarkarKurdish** [uiwjs/react-md-editor#509]
hey, in `EditerMarkdown` there are `components` option that allow you to customize how each element should get rendered

like this

```javascript
      <EditerMarkdown
        components={{
          div: (props) => {
            return <div style={{color: "red"}} {...props} />;
          },
        }}
        source={value}
      />
```

I tired to a custom component so in the editor I can use this like this
```

**Hello world**

<MyComponent />

```
also i've changed the editor code to this
```javascript
      <EditerMarkdown
        components={{
          div: (props) => {
            return <div style={{ color: "red" }} {...props} />;
          },
          MyCustomComponent: <MyCustomComponent />,
        }}
        source={value}
      />

function MyCustomComponent(props) {
  return (
    <div {...props} style={{ width: 30, height: 30, background: "red" }}>
      12345
    </div>
  );
}
```

It neither worked nor have any error and in the preview nothing was rendered for the custom component, is there any way to define a custom component?

**Comment by jaywcjlove** [comment]
It's a little complicated, but not impossible.

1. During the process of converting markdown to html, it was found that `<MyComponent />` stored it.

```jsx
previewOptions={{
    rehypeRewrite={(node, index, parent) => {
      // here ....
    }}
}}
```

2. found your mark

```jsx
previewOptions={{
    div: (props) => {
      if (props['data-MyComponent']) {
        return <MyCustomComponent />
      }
      return <div style={{ color: "red" }} {...props} />;
    },
}}
```

@SarkarKurdish 

https://github.com/uiwjs/react-md-editor/blob/41abfaaee80181fb4cef83ab8ff2e5010d419538/www/src/Markdown.tsx#L9-L44

**Comment by SarkarKurdish** [comment]
> It's a little complicated, but not impossible.
> 
> 1. During the process of converting markdown to html, it was found that `<MyComponent />` stored it.
> 
> ```js
> previewOptions={{
>     rehypeRewrite={(node, index, parent) => {
>       // here ....
>     }}
> }}
> ```
> 
> 2. found your mark
> 
> ```js
> previewOptions={{
>     div: (props) => {
>       if (props['data-MyComponent']) {
>         return <MyCustomComponent />
>       }
>       return <div style={{ color: "red" }} {...props} />;
>     },
> }}
> ```
> 
> @SarkarKurdish
> 
> https://github.com/uiwjs/react-md-editor/blob/41abfaaee80181fb4cef83ab8ff2e5010d419538/www/src/Markdown.tsx#L9-L44

Thanks for the answer, but I could not make any sense of it could you please explain a little more or better of give me an example?

**Comment by jaywcjlove** [comment]
@SarkarKurdish https://codesandbox.io/embed/markdown-editor-for-react-https-github-com-uiwjs-react-md-editor-issues-509-4qqpc6?fontsize=14&hidenavigation=1&theme=dark

Wrote a basic example, hope you can improve it

```jsx
import React from "react";
import ReactDOM from "react-dom";
import MDEditor from "@uiw/react-md-editor";

const MyComponent = () => {
  return <div>这是测试</div>;
};

const mkdStr = `
**Hello world**


<MyComponent />

<MyComponent></MyComponent>

test
`;

function App() {
  const [value, setValue] = React.useState(mkdStr);
  return (
    <div className="container">
      <MDEditor
        height={200}
        previewOptions={{
          rehypeRewrite: (node, index, parent) => {
            if (node.type === "root") {
              console.log("node:", node);
            }
            if (node.tagName === "mycomponent") {
              node.properties["data-mycomp"] = node.tagName;
              node.tagName = "div";

              if (node.children.lenght > 0) {
                // ---> <MyComponent />
              } else {
                // ==> <MyComponent></MyComponent>
              }
            }
          },
          components: {
            div: ({ node, ...props }) => {
              const { "data-mycomp": tagName } = props;
              console.log("node0:", tagName);
              if (tagName === "mycomponent") {
                return <MyComponent />;
              }
              console.log("node1:", node);
              return <div {...props} />;
            }
          }
        }}
        value={value}
        onChange={setValue}
      />
    </div>
  );
}

ReactDOM.render(<App />, document.getElementById("container"));

```

**Comment by jaywcjlove** [comment]
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/1680273/233556423-15c32646-7abb-4018-8e47-d4648c9168a4.png">

**Comment by SarkarKurdish** [comment]
@jaywcjlove Thanks for your help, it's just too complicated to work with in production and as the project gets bigger I don't think this way will scale very well, I ended up using `next-mdx-remote` where the `components` support custom components without any isse (I expected this package to do that as well)

This is my code

```
          <MDXRemote
            {...mdxSource}
            components={{ SyntaxHighlighter, MyComponent }}
          />
```

and this is a markdown example

```
# The title

<MyComponent data={{ name: "Joe" }} />
```

The result is what I've expected the component get's rendered and there is no need to any hacky stuff

**Comment by SarkarKurdish** [comment]
> @jaywcjlove Thanks for your help, it's just too complicated to work with in production and as the project gets bigger I don't think this way will scale very well, I ended up using `next-mdx-remote` where the `components` support custom components without any isse (I expected this package to do that as well)
> 
> This is my code
> 
> ```
>           <MDXRemote
>             {...mdxSource}
>             components={{ SyntaxHighlighter, MyComponent }}
>           />
> ```
> 
> and this is a markdown example
> 
> ```
> # The title
> 
> <MyComponent data={{ name: "Joe" }} />
> ```
> 
> The result is what I've expected the component get's rendered and there is no need to any hacky stuff

forgot to mention I will make a very simple Editor for the markdown myself

**Comment by aysegulkavakli** [comment]
> ```js
>  if (node.type === "root") {
>               console.log("node:", node);
>             }
> ```

I did the same thing but in my example node.type coming "raw". And It doesn't have the attributes like tagName and properties
