### ISSUE TITLE
Changing ordered list type

### ISSUE THREAD

**Issue by bullypb23** [uiwjs/react-md-editor#520]
Hi, is there an option to change the type of ordered list? Or to create a new command for some other type, for example, `type='a'`?

**Comment by jaywcjlove** [comment]
- https://github.com/uiwjs/react-md-editor/issues/514#issuecomment-1536336557
- https://github.com/uiwjs/react-md-editor/issues/454#issuecomment-1305886943
- https://github.com/uiwjs/react-md-editor/issues/214#issuecomment-1239260624
- https://github.com/uiwjs/react-md-editor/issues/366#issuecomment-1092041069
- https://github.com/uiwjs/react-md-editor/issues/380#issuecomment-1116091874
- https://github.com/uiwjs/react-md-editor/issues/509#issuecomment-1517323885
- https://github.com/uiwjs/react-md-editor/issues/366#issuecomment-1092041069
- https://github.com/uiwjs/react-md-editor/issues/348#issuecomment-1049453645
- https://github.com/uiwjs/react-md-editor/issues/445#issuecomment-1285674949

@bullypb23 There are many examples here, you can refer to.
