### ISSUE TITLE
[feat] Word Count?

### ISSUE THREAD

**Issue by rts-gordon** [uiwjs/react-md-editor#522]
Hi there,
   Very lucky to test and use react-md-editor, it's simple and powerful.

   Would you like to impl new feature "Word Count" to count English words and Chinese characters. I think it is a very useful feature. 
   Thank you.

**Comment by jaywcjlove** [comment]
@rts-gordon What kind of API needs to be provided?

**Comment by rts-gordon** [comment]
Hi @jaywcjlove 
  Maybe not API, just show the word count in UI, like this:

![image](https://github.com/uiwjs/react-md-editor/assets/5645296/552ba8d4-841a-4d68-af5f-41dc0ae4854a)

**Comment by jaywcjlove** [comment]
@rts-gordon 

```jsx
<MDEditor
  onStatistics={(data) => {
    console.log('data:', data)
  }}
/>
```

```ts
export interface Statistics extends TextState {
  /** total length of the document */
  length: number;
  /** Get the number of lines in the editor. */
  lineCount: number;
}

export interface TextState {
  text: string;
  selectedText: string;
  selection: TextRange;
}
export interface TextRange {
  start: number;
  end: number;
}
```

**Comment by jaywcjlove** [comment]
@rts-gordon Upgrade `v3.22.0`

**Comment by rts-gordon** [comment]
@jaywcjlove  so fast so  good. I will test the new feature. Thanks a lot.
