### ISSUE TITLE
console.log output coming from Textarea.js

### ISSUE THREAD

**Issue by andrew-goldie** [uiwjs/react-md-editor#523]
On release 3.21.0, a hard-coded console.log statement in Textarea.js is outputting state on every key press. Is it possible for this to be removed or suppressed in some way? (Enjoying using this markdown editor. Thank you).

**Comment by jaywcjlove** [comment]
@andrew-goldie Sorry, I forgot to remove debug. Upgrade `v3.21.1`

**Comment by andrew-goldie** [comment]
Thank you! And again, your component is awesome!
