### ISSUE TITLE
Console.log when click any command in toolbar

### ISSUE THREAD

**Issue by nguyenchi1998** [uiwjs/react-md-editor#529]
On release 3.23.0, when i press any command in toolbar, it will console log like this  state: undefined in file node_modules\@uiw\react-md-editor\esm\commands\index.js  . Is it possible for this to be removed or suppressed in some way? (Enjoying using this markdown editor. Thank you).

**Comment by jaywcjlove** [comment]
@nguyenchi1998 Upgrade v2.23.1
