### ISSUE TITLE
Which of your editors to use?

### ISSUE THREAD

**Issue by Dzoukr** [uiwjs/react-md-editor#532]
Hello, I am a little bit confused which of your awesome libraries to use as "goto" library for React Markdown editor? This one? Or https://github.com/uiwjs/react-markdown-editor?

Thanks for any hint here 🙏

**Comment by jaywcjlove** [comment]
@Dzoukr 
react-md-editor is not suitable for long text loading and display, and there will be performance problems. react-markdown-editor uses codemirror to lazy load long text, and there is no performance problem.

**Comment by Dzoukr** [comment]
Thanks a lot!
