### ISSUE TITLE
[BUG] The bullet list doesn't appear in the preview editor when you make a checklist 

### ISSUE THREAD

**Issue by ianfelix** [uiwjs/react-md-editor#533]
**Bug Description**
As you can see on the video below, the bullet list doesn't show when the checklist is rendered as Markdown.

**Steps to Reproduce**
1. Click on unordered list
2. Add ul list
3. Add checklist
4. See the ul marker disappear

**Environment:**
- Version: 3.23.1

**Additional Context**

https://github.com/uiwjs/react-md-editor/assets/62842327/ba7699ec-b544-462e-b1f9-5b0b6678c48d

**Comment by jaywcjlove** [comment]
@ianfelix Upgrade `v3.23.2`

**Comment by ianfelix** [comment]
It's working now, thanks @jaywcjlove
