### ISSUE TITLE
How do I customize Toolbar and Textarea?

### ISSUE THREAD

**Issue by earthnoob** [uiwjs/react-md-editor#54]
I was having trouble trying to customize some of the components inside the package, namely `Toolbar` and `Teaxarea` (exported from `src/components/Toolbar` and `src/components/Textarea` respectively). When reading through the code, I happened to come across this block: (src/MDEditor.tsx, line 158-165):

```jsx
<Toolbar
    active={{
    fullscreen: this.state.fullscreen,
    preview: this.state.preview,
}}
    prefixCls={prefixCls} commands={commands}
    onCommand={this.handleCommand}
/>
```

I'm wondering if the Toolbar component can be styled through className.

**Comment by jaywcjlove** [comment]
Can you give me a working example?

**Comment by jaywcjlove** [comment]
#83
