### ISSUE TITLE
[Security] Vulnerable to XSS attacks.

### ISSUE THREAD

**Issue by OmkarK45** [uiwjs/react-md-editor#56]
Issue : The textarea doesn't do any validation or sanitize any input to it.

What is happening : This makes editor execute inline html code.

How to reproduce ? : Simply type `<img src onerror="alert('hey!')"/>` in input box

**Comment by OmkarK45** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/45557594/97414985-a99ea780-192a-11eb-9c52-6b6c848f91b7.png)

**Comment by jaywcjlove** [comment]
@OmkarK45 You can try to setting [`previewOptions?: ReactMarkdownProps`](https://github.com/remarkjs/react-markdown/tree/2d991aa1097e95064f0209fc6d3a15b6300c07c7#options);

```jsx
<MDEditor
  value="Hello Markdown!"
  previewOptions={{
  
  }}
/>
```

- `transformLinkUri` - function|null Function that gets called for each encountered link with a single argument - uri. The returned value is used in place of the original. The default link URI transformer acts as an XSS-filter, neutralizing things like javascript:, vbscript: and file: protocols. If you specify a custom function, this default filter won't be called, but you can access it as require('react-markdown').uriTransformer. If you want to disable the default transformer, pass null to this option.
- `escapeHtml` - boolean Setting to false will cause HTML to be rendered (see notes below about proper HTML support). Be aware that setting this to false might cause security issues if the input is user-generated. Use at your own risk. (default: true).
- `skipHtml` - boolean Setting to true will skip inlined and blocks of HTML (default: false).

**Comment by OmkarK45** [comment]
Thank you for replying. I will try this ✌️

**Comment by OmkarK45** [comment]
Update : Your answer fixed the issue. Thanks again. I'm closing the issue now.

**Comment by AntwanSherif** [comment]
@OmkarK45 Can you share with me a code snippet of the settings you used? 
Because adding "<img src onerror="alert('hey!')"/>" to the editor still produces the alert!

**Comment by OmkarK45** [comment]
[image: image.png]

**Comment by OmkarK45** [comment]
[image: image.png]

<MDEditor
            height={400}
            value={value}
            onChange={setValue}
            previewOptions={{
              transformLinkUri: null,
              skipHtml: true,
            }}
          />

**Comment by jaywcjlove** [comment]
- #249
