### ISSUE TITLE
Italic text does not work in preview mode 

### ISSUE THREAD

**Issue by qsdamar** [uiwjs/react-md-editor#573]
Italic text does not work in preview mode, next.js project.

I've looked into the issues and did not find anything similar to this. I understand that `font-style: inherit` is used, but I'm wondering what the initial value of `font-style` should be for this to work.

Does anyone have a similar problem?

These are the libraries and versions I am using:
```
"next": "^12.0.7",
"@uiw/react-md-editor": "^3.6.0",
"next-remove-imports": "^1.0.12",
```

Attaching an image below:
![Screenshot 2023-09-21 at 15 01 59](https://github.com/uiwjs/react-md-editor/assets/56024932/12957327-6933-482f-b7ff-6d402a4ec5a6)

Thank you.

**Comment by jaywcjlove** [comment]
<img width="694" alt="image" src="https://github.com/uiwjs/react-md-editor/assets/1680273/e4c23a2e-5b5e-44bb-9951-c7c4215aec11">

@qsdamar You may have reset `<em>` style. 

```css
em {
    font-style: italic;
}
```

**Comment by qsdamar** [comment]
This helped me to achieve what I wanted. 

Thank you, closing the issue.
