### ISSUE TITLE
The code preview does not show the text after the first line when using the Katex preview

### ISSUE THREAD

**Issue by felipe1120gomez** [uiwjs/react-md-editor#576]
**When you do not use the Katex preview, the blocks or lines of code show all the content**

![image](https://github.com/uiwjs/react-md-editor/assets/69643273/9d5d2d49-8be2-49b3-9900-e856070b06a5)

**But when you use the Katex preview, the blocks or lines of code only show the first line of the content**

![image](https://github.com/uiwjs/react-md-editor/assets/69643273/0e73ce73-74a5-4ce5-b50f-c52786053948)

**As you can see the string is complete and even if you increase the size of the container to min-height: 5rem;
the string is not shown complete**

![image](https://github.com/uiwjs/react-md-editor/assets/69643273/ccd2372b-b04b-4701-ae66-80ebb44ecfc6)

**If you use the mermaid preview this error does not occur**

![image](https://github.com/uiwjs/react-md-editor/assets/69643273/9b962de2-9ddf-4169-8598-21c0d6717503)

**Finally, as you can see, this error occurs in the github [readme](https://uiwjs.github.io/react-md-editor/) so I think it happens in all cases.**

**In my nextJs 13.3 app with "@uiw/react-md-editor": "^3.23.6" also happens**

**Thanks in advance for the help**

**Comment by jaywcjlove** [comment]
@felipe1120gomez https://codesandbox.io/embed/headless-frog-em8yg?fontsize=14&hidenavigation=1&theme=dark


### Support Custom KaTeX Preview

KaTeX is a fast, easy-to-use JavaScript library for TeX math rendering on the web, We perform math rendering through [`KaTeX`](https://github.com/KaTeX/KaTeX).

The following example is preview in [CodeSandbox](https://codesandbox.io/s/markdown-editor-katex-for-react-7v3vl).

[![Open in CodeSandbox](https://img.shields.io/badge/Open%20in-CodeSandbox-blue?logo=codesandbox)](https://codesandbox.io/embed/headless-frog-em8yg?fontsize=14&hidenavigation=1&theme=dark)

> ⚠️ Upgrade v2 to v3 [d025430](https://github.com/uiwjs/react-md-editor/blob/7b9f11ab689a7ea288df3e82c26f4f0e9a53d271/website/ExmapleKaTeX.tsx#L1-L63)

```bash
npm install katex
```

```jsx mdx:preview
import React from "react";
import MDEditor from '@uiw/react-md-editor';
import { getCodeString } from 'rehype-rewrite';
import katex from 'katex';
import 'katex/dist/katex.css';

const mdKaTeX = `This is to display the 
\`\$\$\c = \\pm\\sqrt{a^2 + b^2}\$\$\`
 in one line

\`\`\`KaTeX
c = \\pm\\sqrt{a^2 + b^2}
\`\`\`

\`\`\`css
.w-md-editor-text-input,
.w-md-editor-text-pre > code,
.w-md-editor-text-pre {
  font-size: 2rem !important;
  line-height: 2.5rem !important;
}
\`\`\`
`;

export default function App() {
  const [value, setValue] = React.useState(mdKaTeX);
  return (
    <MDEditor
      value={value}
      onChange={(val) => setValue(val)}
      previewOptions={{
        components: {
          code: ({ inline, children = [], className, ...props }) => {
            const txt = children[0] || '';
            if (inline) {
              if (typeof txt === 'string' && /^\$\$(.*)\$\$/.test(txt)) {
                const html = katex.renderToString(txt.replace(/^\$\$(.*)\$\$/, '$1'), {
                  throwOnError: false,
                });
                return <code dangerouslySetInnerHTML={{ __html: html }} />;
              }
              return <code>{txt}</code>;
            }
            const code = props.node && props.node.children ? getCodeString(props.node.children) : txt;
            if (
              typeof code === 'string' &&
              typeof className === 'string' &&
              /^language-katex/.test(className.toLocaleLowerCase())
            ) {
              const html = katex.renderToString(code, {
                throwOnError: false,
              });
              return <code style={{ fontSize: '150%' }} dangerouslySetInnerHTML={{ __html: html }} />;
            }
            return <code className={String(className)}>{children}</code>;
          },
        },
      }}
    />
  );
}
```

**Comment by jaywcjlove** [comment]
@felipe1120gomez There is a little error in the official example, I modified it.

**Comment by felipe1120gomez** [comment]
Thank you so much
