### ISSUE TITLE
Extra features: Improved/Added commands to match Github, Added line/lines duplication/movement

### ISSUE THREAD

**Issue by RARgames** [uiwjs/react-md-editor#579]
Hey @jaywcjlove,
I've added a few features to your editor (that I needed):
- Enhanced ALL default command buttons (e.g. bold, italic, list) to match Github behavior (e.g. include remove feature)
- Added table, mention, issue, help commands
- Added Ctrl+D to duplicate line/lines
- Added Alt+UpArrow/DownArrow to move line/lines

Feel free to include some/all of them in your project if you think that features are useful. (I can start a PR if you want. Repo is available [here](https://github.com/RARgames/react-md-editor-enhanced). Code is tested and everything should work, some command tests are missing e.g. remove feature.)

To anyone else interested: Feel free to use it, if you need these features.

**Comment by jaywcjlove** [comment]
@RARgames Welcome to submit PR

There are currently too many maintenance items. So if you are interested, you are welcome to submit a PR.

**Comment by RARgames** [comment]
Created #580
