### ISSUE TITLE
Setting a minimum height with auto resize

### ISSUE THREAD

**Issue by erquhart** [uiwjs/react-md-editor#589]
I'm using `height="100%"` to automatically adjust height, which is an amazing feature (thank you)!

It seems the editor can only start at a very very small height when using auto height, `minHeight` doesn't work with it. It's so short that you can't event see the entire cursor:

<img width="648" alt="Screenshot 2023-11-09 at 5 40 44 PM" src="https://github.com/uiwjs/react-md-editor/assets/2112202/8ef10801-b441-470b-9169-429d40dc357c">

I would love to be able to set a minimum height of like 200 for my use case, and I imagine most folks using a markdown editor will want a higher default height as well.

Is it possible to get `minHeight` working so I can set a minimum height? Or at least for the library to provide a better starting height?

Thanks for a great library!

**Comment by jaywcjlove** [comment]
@erquhart Upgrade `v3.25.3`

**Comment by erquhart** [comment]
Holy smokes that was fast, thank you!!
