### ISSUE TITLE
v3.25.3 Getting ref to textarea stopped working

### ISSUE THREAD

**Issue by RARgames** [uiwjs/react-md-editor#590]
After the update from v3.24.1 to 3.25.3 getting ref to textarea stopped working.

This was working, but stopped.
```jsx
<MDEditor
  ref={(node) => {
    if (node && node.textarea) {
      textareaRef.current = node.textarea;
    }
  }}
/>
```

**Comment by jaywcjlove** [comment]
<img width="1080" alt="image" src="https://github.com/uiwjs/react-md-editor/assets/1680273/10b736e2-e06b-4608-90da-d6acac00744c">

I didn't understand what the problem was. Is this an issue with #591 ?
