### ISSUE TITLE
Example stopped working properly - Edit Code Tab

### ISSUE THREAD

**Issue by RARgames** [uiwjs/react-md-editor#591]
Edit code tab looks like this:

![image](https://github.com/uiwjs/react-md-editor/assets/13639766/d2ac78e4-ac2c-4f13-b238-7d878c1ee64b)

There should be content, as in the Live Code tab:

![image](https://github.com/uiwjs/react-md-editor/assets/13639766/1d7c9dab-ce6c-4d08-ac83-f27775b6e7a3)

**Comment by jaywcjlove** [comment]
@RARgames Upgrade `v3.25.4`
