### ISSUE TITLE
Issue with comments using rehype-sanitize on top of react-md-editor

### ISSUE THREAD

**Issue by RARgames** [uiwjs/react-md-editor#593]
I'm just using rehype-sanitize (with default schema, no other rehype/remark plugins for this tests).
Pure rehype-sanitize works correctly, but when it's applied on top of react-md-editor it has an issue with comments.

I cannot track down what is causing the issue, but here is the example:

input:
```
<!-- test --> 123

<!-- test --> 456 <!-- test -->
```
output github/pure rehype-sanitize (Sandbox: https://stackblitz.com/edit/github-ozn1qm?file=src%2Fmain.ts ):
`123 456 `
output using rehype-sanitize on top of react-md-editor:
empty

From debugging using visit somehow `<!-- test --> 456 <!-- test -->` is treated as one object of type `raw` instead of 3 separate objects: `<!-- test -->`, `456`, `<!-- test -->`.

My example (just the important parts):
```jsx
const rehypePlugins = [
  [
    rehypeSanitize,
  ],
];

<MDEditor
  previewOptions={{
    rehypePlugins,
  }}
/>
```

You can also test it in your demo:

![image](https://github.com/uiwjs/react-md-editor/assets/13639766/4392c3de-f7d6-445d-8cb1-652de6185bc6)

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-markdown-preview/blob/74fa8e98070a6ceaeef8055975aefaa3a43e3d4e/core/src/index.tsx#L13-L20

<img width="1186" alt="image" src="https://github.com/uiwjs/react-md-editor/assets/1680273/c4f027d9-2436-45a2-8763-e3189d1bd2ab">


@RARgames  Some plugins are built in by default, which may be caused by them.


You can use [pluginsFilter](https://github.com/uiwjs/react-markdown-preview/blob/74fa8e98070a6ceaeef8055975aefaa3a43e3d4e/core/src/preview.tsx#L18) to clear out the default plugins, or put `rehype-sanitize` at the front of the array and give it a try.

**Comment by RARgames** [comment]
@jaywcjlove I just finished testing it. Plugins seem not to change affect this. (Tested using filters and just to make sure customized version of `react-markdown-preview`: extended test).

Extended test: I removed rehype, remark plugins manually from `react-markdown-preview`. Also I updated `react-markdown` and `rehype-raw`.
Final dependencies:
```
  "dependencies": {
    "@babel/runtime": "^7.17.2",
    "@uiw/copy-to-clipboard": "~1.0.12",
    "react-markdown": "~9.0.1",
    "rehype-raw": "^7.0.0",
    "unist-util-visit": "^4.1.0"
  }
```

Unfortunately, this doesn't fix the issue:
- without rehype-sanitize - text between comments shows
- with rehype-sanitize - text between comments shows doesn't show

Do you have any other ideas of what might be causing it?

**Comment by jaywcjlove** [comment]
https://codesandbox.io/embed/sharp-mountain-m7yx7t?fontsize=14&hidenavigation=1&theme=dark

@RARgames You may need to look for answers in the issues of [rehype-sanitize](https://github.com/rehypejs/rehype-sanitize) and [react-markdown](https://github.com/remarkjs/react-markdown). The above example tells me that the problem does not occur on our side.

**Comment by jaywcjlove** [comment]
@RARgames If you solve it, you can tell us and I will update it in the document, thank you🙏

**Comment by RARgames** [comment]
This is the example that works:
https://codesandbox.io/s/vigilant-williams-glfmzy?fontsize=14&hidenavigation=1&theme=dark

```js
import Markdown from "react-markdown";
import rehypeSanitize from "rehype-sanitize";
import rehypeRaw from "rehype-raw";

const source = `
## MarkdownPreview

**Hello world!!!** <IFRAME SRC=\"javascript:javascript:alert(window.origin);\"></IFRAME>

<!-- test --> 123

<!-- test --> 456 <!-- test -->
`;

const rehypePlugins = [rehypeRaw, rehypeSanitize];

export default function App() {
  return (
    <div className="App">
      <Markdown rehypePlugins={rehypePlugins}>{source}</Markdown>
    </div>
  );
}
```

**Comment by RARgames** [comment]
However using `rehypeRaw` in this place breaks code blocks  - there is an error.
The error can be fixed by additionally using:
```js
const remarkPlugins = [remarkParse, [remarkRehype, { allowDangerousHtml: true }]];
```
There is no error, but code blocks does not show correctly. To fix this we need the order of rehype/remark plugins (not sure).

**Comment by RARgames** [comment]
Here is the final fix:
- Using `rehype-raw` in front of rehypePlugins list (https://github.com/uiwjs/react-markdown-preview/blob/master/core/src/index.tsx)
- Using `rehype-sanitize` as usual

I can prepare a PR, but this requires a bit more knowledge. 
- I tested it on the newest versions of remark/rehype plugins, markdown. Is it ok to update dependencies?
- I'm not sure what this does (https://github.com/uiwjs/react-markdown-preview/blob/master/core/src/plugins/reservedMeta.ts) Is it safe to change `node.data` and `node.data.meta` to `node.properties` and `node.properties.meta`?
- I removed `if (skipHtml) rehypePlugins.push(raw)` (https://github.com/uiwjs/react-markdown-preview/blob/master/core/src/preview.tsx). This might have some conflicts with `rehype-raw` as now it is used always. How to proceed with this?

**Comment by RARgames** [comment]
Created a [PR](https://github.com/uiwjs/react-markdown-preview/pull/248).
The points from the previous comment are valid.
I'll prepare and post custom schema later today.

**Comment by RARgames** [comment]
`highlight line` and `Show Line Numbers` does not work because of the `rehypeRaw`.
Probably, it's again the order of rehype, remark plugins. I'm trying to fix this right now, but without success.

- without `rehype-raw`: `rehype-sanitize` does not work correctly
- after adding `rehype-raw`: `rehype-prism-plus` does not highlight/show lines

**Comment by RARgames** [comment]
@jaywcjlove I already checked it - updating dependencies does not help.

However, I've managed to create a fix in the test env. 
I'll try to implement it in `react-markdown-preview` and submit another PR.
I'll let you know here when it's ready (Also please bump `react-markdown-preview` in `react-md-editor` after the PR).

**Comment by jaywcjlove** [comment]
@RARgames 👌

**Comment by RARgames** [comment]
@jaywcjlove [PR](https://github.com/uiwjs/react-markdown-preview/pull/249) created.

**Comment by jaywcjlove** [comment]
@RARgames Upgrade `v4.0.0`
