### ISSUE TITLE
Upload images using Drag & Drop/paste

### ISSUE THREAD

**Issue by AntwanSherif** [uiwjs/react-md-editor#60]
Is there a way to easily implement image uploading on drag & drop or paste? (Similar to GitHub's user experience)

**Comment by jaywcjlove** [comment]
@AntwanSherif This needs to interact with the backend.

**Comment by AntwanSherif** [comment]
@jaywcjlove Yes I know.. I'm looking for proposals for the frontend logic implementation, or suggestions for integrating with other libraries that provide the functionality like react-dropzone

**Comment by jaywcjlove** [comment]
#83
