### ISSUE TITLE
IMPORTANT MISSING FEATURE: Prop to limit the character length - maxLength and minLength attributes

### ISSUE THREAD

**Issue by invincibleinventor** [uiwjs/react-md-editor#626]
How do I limit the amount of characters (I do not mind if it includes the characters involved in the markdown syntax such as asteriks). Something similar to the maxLength attribute in a textarea maybe? Such a feature would be very relavant in places where one cannot afford to have an infinite amount of text written. Please let me know how could I add such a limit to my MDEditor component or if possible, a prop for controlling minLength and maxLength in the MD textarea. Thanks!

**Comment by jaywcjlove** [comment]
@invincibleinventor The `textareaProps` props can be set

```jsx
import React from "react";
import MDEditor from '@uiw/react-md-editor';

<MDEditor
  value={....}
  textareaProps={{
    placeholder: 'Please enter Markdown text',
    maxLength: 10
  }}
/>
```

**Comment by invincibleinventor** [comment]
Works perfectly! Thanks a lot. Closing this issue...
