### ISSUE TITLE
Shifted text in edit mode

### ISSUE THREAD

**Issue by ArthurKnoep** [uiwjs/react-md-editor#63]
Hi everyone,

When using this awesome component in my NextJS app I ran into a problem where the text cursor is shifted from the "preview text" in the edit mode when using the title tag (the '#')

For example in the following image, the cursor is actually between the 'r' and 'k' of the word 'markdown'
![Capture d’écran de 2020-11-17 22-57-18](https://user-images.githubusercontent.com/27413532/99455854-b9594c80-2928-11eb-9285-b97ca8fc55af.png)

If that is of any help, here is my next.config.js:
```js
const withSass = require('@zeit/next-sass');
const withCSS = require('@zeit/next-css')
const withPlugins = require('next-compose-plugins');

const sassConfig = {
    cssModules: true,
    cssLoaderOptions: {
        camelCase: true
    }
};
const cssConfig = {
    cssModules: false,
};

module.exports = withPlugins([
    [withSass, sassConfig],
    [withCSS, cssConfig],
])

```

Thanks in advance for your help

**Comment by BrutomFR** [comment]
I have the same problem.
I did not find a solution

**Comment by jaywcjlove** [comment]
There is no instance, it can only be judged that it may be a style conflict

**Comment by MatheusPires99** [comment]
@ArthurKnoep @BrutomFR  I had the same problem as well, so I stated to look at the CSS properties that is applied and I found a `line-height: 18px;` on the element with class`.w-md-editor-text`. So a set the `line-height` of this element to `unset`, and that resolved my problem.

**Comment by StephenGrider** [comment]
The editor uses Prism to apply syntax highlighting, see here: https://github.com/uiwjs/react-md-editor/blob/master/src/components/TextArea/index.tsx#L56

Prism itself applies some classnames to elements to get the syntax highlighting effect. Unfortunately, those classnames are extremely common and generic - stuff like `title`, `token`, etc. 

Here's the crux: if you have any CSS that affects those classNames it'll interfere with Prism's default styling! So @ArthurKnoep, you probably have a `.title` css rule somewhere that is increasing the font size of that `# hello` text.

There's no option in this lib to disable the highlighting stuff, but you can sabotage prism directly to keep it from doing any highlighting:

```
import Prism from 'prismjs';

Prism.languages.markdown = {};
```

**Comment by ArthurKnoep** [comment]
Thanks @StephenGrider, @MatheusPires99 and @jaywcjlove for your answer.

Indeed it was a style conflict, the responsible in my case was bulma (damn it bulma).

If someone passes by here with the same problem, here's my fix:

```css
.w-md-editor .title {
    line-height: unset !important;
    font-size: unset !important;
    font-weight: unset !important;
}
```

**Comment by rafaelguedes** [comment]
@ArthurKnoep, how do you manage to add that syntax highlighting? 

I mean: how do you manage to type "# hello" and apply the heading style in the "hello" word?

**Comment by ArthurKnoep** [comment]
Hey, sorry for the late reply.

Actually this was a big induced by a conflicting style caused by bulma. This is not something that is desirable because it breaks the lines alignment.
