### ISSUE TITLE
code highlight and rendering style seems not to work well in mac m1

### ISSUE THREAD

**Issue by steveoni** [uiwjs/react-md-editor#636]
This site(https://www.scatterednote.com/steveoni/notes/rust_cargo%20and%20crates_notes) currently uses both react-md-editor and react-markdown-preview, when viewed in any of the browsers (chrome and safari) on Mac silicon chip, the markdown rendering especially the code-highlight seems not to work perfectly.

![image](https://github.com/uiwjs/react-md-editor/assets/20904032/11178e73-580a-4e82-a77e-3cdc829f96a4)

I load this on my phone and it shows properly.

![IMG_0882](https://github.com/uiwjs/react-md-editor/assets/20904032/a3e88b8c-1afe-43bf-bbc4-5108d706e9e4)

I don't have another system to debug the issue properly.

and here is the code rendering the above images

https://github.com/scatteredNote/scatteredNote/blob/a275f5b2271170f7b68faa5256a88c55c9e2e049/pages/%5Buser%5D/notes/%5Bslug%5D.js#L72

also the CSS

https://github.com/scatteredNote/scatteredNote/blob/a275f5b2271170f7b68faa5256a88c55c9e2e049/styles/globals.css#L5

**Comment by jaywcjlove** [comment]
@steveoni  

https://github.com/uiwjs/react-md-editor/blob/bc85ed2a11793ed052e9a68d423841c707d0f282/core/README.md?plain=1#L865-L885
