### ISSUE TITLE
有没有办法自定义一个toolbar组件 点击弹出dialog 的效果 而不是内嵌到toolbar children 里面的？

### ISSUE THREAD

**Issue by MarryYou** [uiwjs/react-md-editor#641]
我这边想尝试利用编辑器做一个AIGC,看了官方示例都是内嵌类型的，想实现类似于下面的效果可以吗？
<img width="1290" alt="截屏2024-05-15 23 28 04" src="https://github.com/uiwjs/react-md-editor/assets/17715691/287f6798-3c7e-4bf5-9eea-e1f30f884d46">

**Comment by jaywcjlove** [comment]
@MarryYou 内嵌到 toolbar children 是方便 dialog 定位位置，当然可以放到外面需要自己实现的代码就多一些，这需要自己去实现

**Comment by MarryYou** [comment]
@jaywcjlove 好的  多谢多谢！！
