### ISSUE TITLE
https://uiwjs.github.io/react-md-editor/ Doesn't load

### ISSUE THREAD

**Issue by IPWright83** [uiwjs/react-md-editor#648]
I thought I'd try and check out the demo site https://uiwjs.github.io/react-md-editor/ Doesn't load, but it's currently failing to load, looks like the React import is broken for some reason?

Within Example.tsx:
`TypeError: Cannot read properties of null (reading 'useState')`

**Comment by jaywcjlove** [comment]
@IPWright83  Thank you for the reminder, I have fixed it.

**Comment by IPWright83** [comment]
Thanks @jaywcjlove 🙂
