### ISSUE TITLE
The HTML style tag can change the style of elements on the page

### ISSUE THREAD

**Issue by yuryYudanau** [uiwjs/react-md-editor#649]
If you insert **<style>body{display:none;}</style>** into the editor, the page disappears.

**Comment by jaywcjlove** [comment]
@yuryYudanau 

https://github.com/uiwjs/react-md-editor/blob/2520e88123bde4f4d31415bb362183964f94ca48/core/README.md?plain=1#L596-L604

**Comment by yuryYudanau** [comment]
Thank you. It works
