### ISSUE TITLE
Formatting of paragraphs

### ISSUE THREAD

**Issue by linneagerhardsson** [uiwjs/react-md-editor#66]
I have issues with formatting of the paragraphs when using the editor, when using 

```jsx
<div className="row">
  {edit ? <MDEditor value={value} onChange={setValue} /> : <MDEditor.Markdown source={value} />}
</div>
<div className="row">
  <ReactMarkdown plugins={[gfm]} children={value} />
</div>
```

the result looks like this which is not what you expect. I want to show the input to my editor as two paragraphs, but the editor doesn't seem to format the paragraphs so that it can be shown as paragraphs? 

![image](https://user-images.githubusercontent.com/22499594/101150335-67027600-3620-11eb-839b-3428dc0185eb.png)

**Comment by jaywcjlove** [comment]
@linneagerhardsson Upgrade `+ @uiw/react-md-editor@2.0.0`, support `plugins `.
