### ISSUE TITLE
我本地用的react17版本 能用咱们的编辑组件吗

### ISSUE THREAD

**Issue by jingqiu2180** [uiwjs/react-md-editor#666]
我本地用的react17版本 能用咱们的编辑组件吗 我能安装咱们的哪个版本

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/2520e88123bde4f4d31415bb362183964f94ca48/core/package.json#L65-L67

@jingqiu2180 理论上可以使用，你可以测试一下
