### ISSUE TITLE
Scroll on empty editor

### ISSUE THREAD

**Issue by ShamansCoding** [uiwjs/react-md-editor#67]
Greetings! 

As mentioned in the name of the issue, the scroll is always enabled in the editor. Even when there is no text in it.

I couldn't found a way to fix it from available props. Can this behavior be fixed by default in the future, or where is some way to do it right now?
![Запись экрана 2020-12-05 в 02 58 03](https://user-images.githubusercontent.com/28977555/101226836-d327bd00-36a6-11eb-956d-47bc88539b46.gif)

**Comment by jaywcjlove** [comment]
@ShamansCoding Upgrade `+ @uiw/react-md-editor@1.14.7`

**Comment by ShamansCoding** [comment]
@jaywcjlove Thanks! Timely release!
