### ISSUE TITLE
Bold text is not working as expected

### ISSUE THREAD

**Issue by ppascualv** [uiwjs/react-md-editor#68]
If a user writes **bold text ** is shown bold in the preview but it shouldn't be according to MD specification.
Moreover, the MD renderer that this library is using https://remarkjs.github.io/react-markdown/ is working fine.

![image](https://user-images.githubusercontent.com/2453682/101245656-92638e80-370e-11eb-8a33-548dd583e7a4.png)

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/101281933-12701e00-380d-11eb-9a24-f33996271656.png)

@ppascualv Don't understand your question.

**Comment by ppascualv** [comment]
The issue happens when you add a white space between the character and the asterisk it keeps the bold text and it shouldn't.

**Comment by jaywcjlove** [comment]
@ppascualv I need to upgrade [react-markdown](https://github.com/uiwjs/react-markdown-preview/blob/ceb72974332942372c85bcb37b036b4185314459/package.json#L49) to v5.0.3

**Comment by jaywcjlove** [comment]
@ppascualv Upgrade `+ @uiw/react-md-editor@2.0.0`

**Comment by ppascualv** [comment]
@jaywcjlove I updated to version 2 and seems that updating the value prop does not change the shown value.

<MDEditor
        value={value} // Updating this value is not reflected on the editor
</>

**Comment by jaywcjlove** [comment]
@ppascualv Upgrade `+ @uiw/react-md-editor@2.0.1`
