### ISSUE TITLE
Spellcheck attribute does not work

### ISSUE THREAD

**Issue by evnz** [uiwjs/react-md-editor#69]
Spellcheck attribute does not propagate down to the TextArea and so it doesn't work.

**Comment by jaywcjlove** [comment]
@evnz ??? did not get your point.

https://github.com/uiwjs/react-md-editor/blob/1d7161def211e2a3e7060c51ee82a9293450ff03/src/Editor.tsx#L158-L171

**Comment by evnz** [comment]
@jaywcjlove thanks for clarifying, I was passing the spellcheck attribute in the wrong way 🤦 

I was doing

```typescript
 <MDEditor
        spellCheck={true}
        autoFocus={props.autoFocus}
        preview="edit"
        value={props.input}
        onChange={(detail) => props.onChange(detail!)}
 />
```
^Which is the incorrect way

instead of 

```typescript
<MDEditor
        textareaProps={
            {spellCheck:"true"}
        }
        autoFocus={props.autoFocus}
        preview="edit"
        value={props.input}
        onChange={(detail) => props.onChange(detail!)}
/>
```
