### ISSUE TITLE
How do I upload images?

### ISSUE THREAD

**Issue by TheStarkor** [uiwjs/react-md-editor#83]
I have an upload server (https://.../upload/img) that returns an image's URL and I found the `commands.image`.

I want to modify the commands that can upload an image(how to..?) and return `![](res.url)`(I can do it with `execute`)

Can I add components like the figure?

![image](https://user-images.githubusercontent.com/45455072/103614534-2756e300-4f6c-11eb-90d1-3979d8e3828b.png)

**Comment by jaywcjlove** [comment]
@TheStarkor Definition tool reference: #85 

```tsx
import React from "react";
import ReactDOM from "react-dom";
import MDEditor, { commands, ICommand, TextState, TextApi } from '@uiw/react-md-editor';

const title3: ICommand = {
  name: 'title3',
  keyCommand: 'title3',
  buttonProps: { 'aria-label': 'Insert title3' },
  icon: (
    <svg width="12" height="12" viewBox="0 0 520 520">
      <path fill="currentColor" d="M15.7083333,468 C7.03242448,468 0,462.030833 0,454.666667 L0,421.333333 C0,413.969167 7.03242448,408 15.7083333,408 L361.291667,408 C369.967576,408 377,413.969167 377,421.333333 L377,454.666667 C377,462.030833 369.967576,468 361.291667,468 L15.7083333,468 Z M21.6666667,366 C9.69989583,366 0,359.831861 0,352.222222 L0,317.777778 C0,310.168139 9.69989583,304 21.6666667,304 L498.333333,304 C510.300104,304 520,310.168139 520,317.777778 L520,352.222222 C520,359.831861 510.300104,366 498.333333,366 L21.6666667,366 Z M136.835938,64 L136.835937,126 L107.25,126 L107.25,251 L40.75,251 L40.75,126 L-5.68434189e-14,126 L-5.68434189e-14,64 L136.835938,64 Z M212,64 L212,251 L161.648438,251 L161.648438,64 L212,64 Z M378,64 L378,126 L343.25,126 L343.25,251 L281.75,251 L281.75,126 L238,126 L238,64 L378,64 Z M449.047619,189.550781 L520,189.550781 L520,251 L405,251 L405,64 L449.047619,64 L449.047619,189.550781 Z" />
    </svg>
  ),
  execute: (state: TextState, api: TextApi) => {
    let modifyText = `### ${state.selectedText}\n`;
    if (!state.selectedText) {
      modifyText = `### `;
    }
    api.replaceSelection(modifyText);
  },
};

export default function App() {
  const [value, setValue] = React.useState("**Hello world!!!**");
  return (
    <div className="container">
      <MDEditor
        value="Hello Markdown!"
        commands={[
          commands.bold, commands.hr, commands.italic, commands.divider, commands.codeEdit, commands.codeLive, commands.codePreview, commands.divider,
          commands.fullscreen, 
          // Custom Toolbars
          title3,
        ]}
      />
    </div>
  );
}
```

**Comment by TheStarkor** [comment]
Thank you for answering @jaywcjlove.

I read that and added some needed commands.

What I need is

```javascript
const image = {
  name: 'image',
  keyCommand: 'image',
  buttonProps: { 'aria-label': 'Insert image' },
  icon: (
    <svg width="12" height="12" viewBox="0 0 520 520">
      <path fill="currentColor" d="M15.7083333,468 C7.03242448,468 0,462.030833 0,454.666667 L0,421.333333 C0,413.969167 7.03242448,408 15.7083333,408 L361.291667,408 C369.967576,408 377,413.969167 377,421.333333 L377,454.666667 C377,462.030833 369.967576,468 361.291667,468 L15.7083333,468 Z M21.6666667,366 C9.69989583,366 0,359.831861 0,352.222222 L0,317.777778 C0,310.168139 9.69989583,304 21.6666667,304 L498.333333,304 C510.300104,304 520,310.168139 520,317.777778 L520,352.222222 C520,359.831861 510.300104,366 498.333333,366 L21.6666667,366 Z M136.835938,64 L136.835937,126 L107.25,126 L107.25,251 L40.75,251 L40.75,126 L-5.68434189e-14,126 L-5.68434189e-14,64 L136.835938,64 Z M212,64 L212,251 L161.648438,251 L161.648438,64 L212,64 Z M378,64 L378,126 L343.25,126 L343.25,251 L281.75,251 L281.75,126 L238,126 L238,64 L378,64 Z M449.047619,189.550781 L520,189.550781 L520,251 L405,251 L405,64 L449.047619,64 L449.047619,189.550781 Z" />
    </svg>
  ),
  execute: async (state, api) => {
    // OPEN my component. 

    // example
    // const [image, setImaeg] = React.useState('');
    // <ImageUploader value={image} onChange={setImage} />

    let image_url = await upload_image(image);

    let modifyText = `![](${image_url})\n`;
    api.replaceSelection(modifyText);
  },
};
```

1. I click my custom button. (like title3)
2. Show my component that can upload an image like the figure.
3. Get image buffer and upload.
4. Modify text.

Can I open a component below the button(commands)?

**Comment by jaywcjlove** [comment]
@TheStarkor I need to expand this

![image](https://user-images.githubusercontent.com/1680273/103843852-88e59180-50d3-11eb-9c89-71d82697bd64.png)

Do you need such an effect?

**Comment by TheStarkor** [comment]
Yes! That's what I want.

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/blob/70760fd5c621868203ca7867f652fe196ec3f4ed/website/ExampleCustomToolbar.tsx#L1-L55

Upgrade `+ @uiw/react-md-editor@2.1.0`

**Comment by jaywcjlove** [comment]
@TheStarkor Example: https://codesandbox.io/s/dazzling-resonance-m08m7

**Comment by R3D-Z3R0** [comment]
Hello @jaywcjlove  the example is not working and we wanted to implement a small drag & drop it 
![2021-07-22 17_11_24-React Typescript - CodeSandbox](https://user-images.githubusercontent.com/61193623/126663188-54b424e6-2440-495d-a248-408c77ae72f4.png)
into our markdown

**Comment by jmvalino** [comment]
hi @jaywcjlove  can you give more example on how to achieve this functionality ? Thanks

**Comment by killerbytes** [comment]
How to implement with a custom component eg: Modal?

**Comment by dino3616** [comment]
Hi, I have tried to implement a way to upload an image by Drag&Drop directly into the editor or by Copy&Paste and display it in the preview.
It may not be a very pretty method, but I hope it will be useful to you.
Here's my [EXAMPLE](https://codesandbox.io/s/react-md-editor-d-d-ihwzqm)!

```typescript
import MDEditor from '@uiw/react-md-editor';
import { useState } from 'react';
import onImagePasted from './utils/onImagePasted';
import '@uiw/react-md-editor/markdown-editor.css';
import '@uiw/react-markdown-preview/markdown.css';

const MdEditor = () => {
  const [markdown, setMarkdown] = useState<string | undefined>();

  return (
    <div data-color-mode="light">
      <MDEditor
        value={markdown}
        onChange={(value) => {
          setMarkdown(value);
        }}
        onPaste={async (event) => {
          await onImagePasted(event.clipboardData, setMarkdown);
        }}
        onDrop={async (event) => {
          await onImagePasted(event.dataTransfer, setMarkdown);
        }}
        height={440}
        textareaProps={{
          placeholder: 'Fill in your markdown for the coolest of the cool.',
        }}
        hideToolbar
      />
    </div>
  );
};

export default MdEditor;
```

```typescript
import type { SetStateAction } from 'react';
import { fileUpload } from '../../../../../libs/firebase/storage';
import insertToTextArea from './insertToTextArea';

const onImagePasted = async (dataTransfer: DataTransfer, setMarkdown: (value: SetStateAction<string | undefined>) => void) => {
  const files: File[] = [];
  for (let index = 0; index < dataTransfer.items.length; index += 1) {
    const file = dataTransfer.files.item(index);

    if (file) {
      files.push(file);
    }
  }

  await Promise.all(
    files.map(async (file) => {
      const url = await fileUpload(file);
      const insertedMarkdown = insertToTextArea(`![](${url})`);
      if (!insertedMarkdown) {
        return;
      }
      setMarkdown(insertedMarkdown);
    }),
  );
};

export default onImagePasted;
```

```typescript
const insertToTextArea = (intsertString: string) => {
  const textarea = document.querySelector('textarea');
  if (!textarea) {
    return null;
  }

  let sentence = textarea.value;
  const len = sentence.length;
  const pos = textarea.selectionStart;
  const end = textarea.selectionEnd;

  const front = sentence.slice(0, pos);
  const back = sentence.slice(pos, len);

  sentence = front + intsertString + back;

  textarea.value = sentence;
  textarea.selectionEnd = end + intsertString.length;

  return sentence;
};

export default insertToTextArea;
```

**Comment by dibasdauliya** [comment]
> @TheStarkor Example: https://codesandbox.io/s/dazzling-resonance-m08m7

getting `TypeError: handle.getState is not a function` error

**Comment by nguyenvietdung31** [comment]
> Thank you for answering @jaywcjlove.
> 
> What I need is
> 
> ```js
> const image = {
>   name: 'image',
>   keyCommand: 'image',
>   buttonProps: { 'aria-label': 'Insert image' },
>   icon: (
>     <svg width="12" height="12" viewBox="0 0 520 520">
>       <path fill="currentColor" d="M15.7083333,468 C7.03242448,468 0,462.030833 0,454.666667 L0,421.333333 C0,413.969167 7.03242448,408 15.7083333,408 L361.291667,408 C369.967576,408 377,413.969167 377,421.333333 L377,454.666667 C377,462.030833 369.967576,468 361.291667,468 L15.7083333,468 Z M21.6666667,366 C9.69989583,366 0,359.831861 0,352.222222 L0,317.777778 C0,310.168139 9.69989583,304 21.6666667,304 L498.333333,304 C510.300104,304 520,310.168139 520,317.777778 L520,352.222222 C520,359.831861 510.300104,366 498.333333,366 L21.6666667,366 Z M136.835938,64 L136.835937,126 L107.25,126 L107.25,251 L40.75,251 L40.75,126 L-5.68434189e-14,126 L-5.68434189e-14,64 L136.835938,64 Z M212,64 L212,251 L161.648438,251 L161.648438,64 L212,64 Z M378,64 L378,126 L343.25,126 L343.25,251 L281.75,251 L281.75,126 L238,126 L238,64 L378,64 Z M449.047619,189.550781 L520,189.550781 L520,251 L405,251 L405,64 L449.047619,64 L449.047619,189.550781 Z" />
>     </svg>
>   ),
>   execute: async (state, api) => {
>     // OPEN my component. 
> 
>     // example
>     // const [image, setImaeg] = React.useState('');
>     // <ImageUploader value={image} onChange={setImage} />
> 
>     let image_url = await upload_image(image);
> 
>     let modifyText = `![](${image_url})\n`;
>     api.replaceSelection(modifyText);
>   },
> };
> ```
> 
> 1. I click my custom button. (like title3)
> 2. Show my component that can upload an image like the figure.
> 3. Get image buffer and upload.
> 4. Modify text.
> 
> Can I open a component below the button(commands)?

can you share the code that open your component (e.g a modal) ?

**Comment by BarrySong97** [comment]
> Hi, I have tried to implement a way to upload an image by Drag&Drop directly into the editor or by Copy&Paste and display it in the preview. It may not be a very pretty method, but I hope it will be useful to you. Here's my [EXAMPLE](https://codesandbox.io/s/react-md-editor-d-d-ihwzqm)!
> 
> ```ts
> import MDEditor from '@uiw/react-md-editor';
> import { useState } from 'react';
> import onImagePasted from './utils/onImagePasted';
> import '@uiw/react-md-editor/markdown-editor.css';
> import '@uiw/react-markdown-preview/markdown.css';
> 
> const MdEditor = () => {
>   const [markdown, setMarkdown] = useState<string | undefined>();
> 
>   return (
>     <div data-color-mode="light">
>       <MDEditor
>         value={markdown}
>         onChange={(value) => {
>           setMarkdown(value);
>         }}
>         onPaste={async (event) => {
>           await onImagePasted(event.clipboardData, setMarkdown);
>         }}
>         onDrop={async (event) => {
>           await onImagePasted(event.dataTransfer, setMarkdown);
>         }}
>         height={440}
>         textareaProps={{
>           placeholder: 'Fill in your markdown for the coolest of the cool.',
>         }}
>         hideToolbar
>       />
>     </div>
>   );
> };
> 
> export default MdEditor;
> ```
> 
> ```ts
> import type { SetStateAction } from 'react';
> import { fileUpload } from '../../../../../libs/firebase/storage';
> import insertToTextArea from './insertToTextArea';
> 
> const onImagePasted = async (dataTransfer: DataTransfer, setMarkdown: (value: SetStateAction<string | undefined>) => void) => {
>   const files: File[] = [];
>   for (let index = 0; index < dataTransfer.items.length; index += 1) {
>     const file = dataTransfer.files.item(index);
> 
>     if (file) {
>       files.push(file);
>     }
>   }
> 
>   await Promise.all(
>     files.map(async (file) => {
>       const url = await fileUpload(file);
>       const insertedMarkdown = insertToTextArea(`![](${url})`);
>       if (!insertedMarkdown) {
>         return;
>       }
>       setMarkdown(insertedMarkdown);
>     }),
>   );
> };
> 
> export default onImagePasted;
> ```
> 
> ```ts
> const insertToTextArea = (intsertString: string) => {
>   const textarea = document.querySelector('textarea');
>   if (!textarea) {
>     return null;
>   }
> 
>   let sentence = textarea.value;
>   const len = sentence.length;
>   const pos = textarea.selectionStart;
>   const end = textarea.selectionEnd;
> 
>   const front = sentence.slice(0, pos);
>   const back = sentence.slice(pos, len);
> 
>   sentence = front + intsertString + back;
> 
>   textarea.value = sentence;
>   textarea.selectionEnd = end + intsertString.length;
> 
>   return sentence;
> };
> 
> export default insertToTextArea;
> ```

great job, my friend

**Comment by PanditSiddharth** [comment]
> https://github.com/uiwjs/react-md-editor/blob/70760fd5c621868203ca7867f652fe196ec3f4ed/website/ExampleCustomToolbar.tsx#L1-L55
> 
> Upgrade `+ @uiw/react-md-editor@2.1.0`

You can use ...commands.getCommands() to get all already created commands
