### ISSUE TITLE
Typo in the CodeSandbox Demo

### ISSUE THREAD

**Issue by jannaee** [uiwjs/react-md-editor#92]
If you go to the README.md file, and select the first link to open the code in [Codesandbox](https://codesandbox.io/s/markdown-editor-for-react-izdd6?file=/index.js:61-105)
You will see on lines 3, 35 and 37 packages are being imported from `MEDitor `vs `MDEditor`.

`import MEDitor from "@uiw/react-md-editor";`

should be

`import MDEditor from "@uiw/react-md-editor";`

**Comment by jaywcjlove** [comment]
@jannaee thx!
