### ISSUE TITLE
Text area doesn't update after render if we update the value by api

### ISSUE THREAD

**Issue by raha1923** [uiwjs/react-md-editor#94]
I'm using this package in one of my projects. Everything is ok if I render the package and start typing markdown content in it but if I just click on a button after the render to get markdown data from the internet (or anywhere else) and then send it down to the component using the props, the preview works fine but the text area would be empty.

**Comment by jaywcjlove** [comment]
@raha1923 Upgrade `+ @uiw/react-md-editor@2.1.2`, thx!

**Comment by raha1923** [comment]
wow, thank you a lot, such a quick reaction and response.

great.
