### ISSUE TITLE
Value not update the text area

### ISSUE THREAD

**Issue by raaynaldo** [uiwjs/react-md-editor#96]
Is there any way to update the text area? because it is just updating the markdown preview.

**Comment by jaywcjlove** [comment]
@raaynaldo  Example: https://codesandbox.io/s/markdown-editor-for-react-96-luk07?file=/index.js:0-578

```jsx
import React from "react";
import ReactDOM from "react-dom";
import MDEditor from "@uiw/react-md-editor";

function App() {
  const [value, setValue] = React.useState(`# title`);
  return (
    <div className="container">
      <MDEditor height={200} value={value} onChange={setValue} />
      <input
        type="text"
        onChange={(e) => {
          setValue(e.target.value);
        }}
      />
      <div style={{ padding: "50px 0 0 0" }} />
      <MDEditor.Markdown source={value} />
    </div>
  );
}

ReactDOM.render(<App />, document.getElementById("container"));
```

**Comment by raaynaldo** [comment]
Thank you for your response. Yeah this is working when using `"@uiw/react-md-editor": "1.13.1",` version. I just figured it out. Is it possible to use the last version?

**Comment by jaywcjlove** [comment]
@raaynaldo `@uiw/react-md-editor v2.1.2`

https://codesandbox.io/s/markdown-editor-for-react-96-luk07?file=/index.js:0-578

**Comment by raaynaldo** [comment]
Hi @jaywcjlove , sorry it is my bad, suddenly is working after I update again. I think I missed something before. Thanks for you help, and this is cool stuff! Appreciate it.
