### ISSUE TITLE
Preview Props

### ISSUE THREAD

**Issue by raaynaldo** [uiwjs/react-md-editor#99]
I get an error when I try to send Preview props `preview={"preview"}`.

this is my full code
```js
<MDEditor
  value={value}
  onChange={handleChange}
  visiableDragbar={false}
  autoFocus={false}
  preview={"preview"}
/>
```

![image](https://user-images.githubusercontent.com/22878284/105947452-21b65f80-6037-11eb-80de-3e1085ae340e.png)

**Comment by jaywcjlove** [comment]
@raaynaldo Upgrade `+ @uiw/react-md-editor@2.1.3`

**Comment by jaywcjlove** [comment]
@raaynaldo https://codesandbox.io/s/markdown-editor-for-react-99-7ulng

**Comment by raaynaldo** [comment]
Thank you @jaywcjlove
